"""Terrain road-network endpoint — serves the static per-theater gz data
generated by tools/extract_terrain.py."""

import gzip
import json
import os

import pytest

from app import app

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "terrain")


@pytest.fixture
def client():
    app.config["TESTING"] = True
    with app.test_client() as c:
        yield c


def test_unknown_theater_404s(client):
    resp = client.get("/api/terrain/Narnia/roads")
    assert resp.status_code == 404


def test_bad_theater_name_rejected(client):
    resp = client.get("/api/terrain/..%2f..%2fapp/roads")
    assert resp.status_code in (400, 404)


@pytest.mark.skipif(
    not os.path.exists(os.path.join(DATA_DIR, "Kola.roads.json.gz")),
    reason="Kola terrain data not generated")
def test_kola_roads_served_gzipped(client):
    resp = client.get("/api/terrain/Kola/roads")
    assert resp.status_code == 200
    assert resp.headers.get("Content-Encoding") == "gzip"
    # Flask's test client does not auto-inflate; do it by hand and check the
    # payload shape the frontend layer expects.
    data = json.loads(gzip.decompress(resp.data))
    assert data["theater"] == "Kola"
    assert isinstance(data["classes"], list) and data["classes"]
    assert isinstance(data["lines"], list) and len(data["lines"]) > 1000
    cls_idx, coords = data["lines"][0]
    assert 0 <= cls_idx < len(data["classes"])
    lat, lon = coords[0]
    # Kola theater bounds
    assert 60 < lat < 75 and 5 < lon < 45
