-- ============================================================================
-- CivTraffic-Caucasus.lua - custom civilian air traffic for the Caucasus map
-- Curated real-world corridors, infinite runtime spawning, F10-controllable.
-- INSTALL: Mission Editor -> new trigger: MISSION START -> DO SCRIPT FILE ->
--          this file. Requires: Civil Aircraft Mod installed; country EGYPT
--          placed in the NEUTRALS coalition (ME coalition setup).
-- Generated by gen_civtraffic_lua.py - edit the CFG table freely.
-- ============================================================================

CivTrafficCFG = {
  mapName = "Caucasus",
  country = "EGYPT",
  maxActive = 64,
  density = 0.6,
  lanes = {
    {
      name = "M1E",
      cad = 1200,
      speed = 236.1,
      fls = { 9449, 10668, 11887 },
      types = { "B_747", "A_330", "B_757", "B_737", "A_320" },
      fixes = {
        {
          x = -527214,
          y = 121683
        },
        {
          x = -457138,
          y = 421980
        },
        {
          x = -407236,
          y = 576586
        },
        {
          x = -392304,
          y = 701234
        },
        {
          x = -357401,
          y = 860317
        },
        {
          x = -372303,
          y = 973757
        },
        {
          x = -392249,
          y = 1068474
        },
      },
      offramps = {
        {
          p = 0.2,
          trunc = 5,
          airdrome = 29,
          apos = {
            x = -315671,
            y = 896630
          },
          via = {
            x = -330000,
            y = 872000
          },
          viaAlt = 3500
        },
      }
    },
    {
      name = "M1W",
      cad = 2000,
      speed = 236.1,
      fls = { 9144, 10363, 11582 },
      types = { "B_747", "A_330", "B_757", "B_737", "A_320" },
      fixes = {
        {
          x = -377751,
          y = 1071526
        },
        {
          x = -357697,
          y = 976243
        },
        {
          x = -342599,
          y = 859683
        },
        {
          x = -377696,
          y = 698766
        },
        {
          x = -392764,
          y = 573414
        },
        {
          x = -442862,
          y = 418020
        },
        {
          x = -512786,
          y = 118317
        },
      },
      offramps = {  }
    },
    {
      name = "B2E",
      cad = 1200,
      speed = 236.1,
      fls = { 9449, 10668, 11887 },
      types = { "B_737", "A_320", "B_757", "A_330" },
      fixes = {
        {
          x = -337408,
          y = -200082
        },
        {
          x = -342408,
          y = 249938
        },
        {
          x = -344201,
          y = 606739
        },
        {
          x = -305257,
          y = 681489
        },
        {
          x = -314324,
          y = 798890
        },
        {
          x = -337020,
          y = 897634
        },
        {
          x = -364751,
          y = 958951
        },
      },
      offramps = {
        {
          p = 0.25,
          trunc = 4,
          airdrome = 25,
          apos = {
            x = -284887,
            y = 683859
          },
          via = {
            x = -288000,
            y = 668000
          },
          viaAlt = 2200
        },
        {
          p = 0.25,
          trunc = 6,
          airdrome = 29,
          apos = {
            x = -315671,
            y = 896630
          },
          via = {
            x = -322000,
            y = 880000
          },
          viaAlt = 3500
        },
      }
    },
    {
      name = "B2W",
      cad = 2100,
      speed = 236.1,
      fls = { 9144, 10363, 11582 },
      types = { "B_737", "A_320", "B_757", "A_330" },
      fixes = {
        {
          x = -351249,
          y = 965049
        },
        {
          x = -322980,
          y = 902366
        },
        {
          x = -299676,
          y = 801110
        },
        {
          x = -290743,
          y = 678511
        },
        {
          x = -329799,
          y = 603261
        },
        {
          x = -327592,
          y = 250062
        },
        {
          x = -322592,
          y = -199918
        },
      },
      offramps = {
        {
          p = 0.33,
          trunc = 5,
          airdrome = 22,
          apos = {
            x = -355811,
            y = 617386
          },
          via = {
            x = -348000,
            y = 610000
          },
          viaAlt = 2000
        },
      }
    },
    {
      name = "W8E",
      cad = 1800,
      speed = 236.1,
      fls = { 10058, 11278, 12497 },
      types = { "B_747", "A_330", "B_757", "B_737", "A_320" },
      fixes = {
        {
          x = -386338,
          y = -476164
        },
        {
          x = -156639,
          y = -96713
        },
        {
          x = -26005,
          y = 234338
        },
        {
          x = 96308,
          y = 336422
        },
        {
          x = 317468,
          y = 416962
        },
      },
      offramps = {  }
    },
    {
      name = "W8W",
      cad = 2400,
      speed = 236.1,
      fls = { 9754, 10973, 12192 },
      types = { "B_747", "A_330", "B_757", "B_737", "A_320" },
      fixes = {
        {
          x = 322532,
          y = 403038
        },
        {
          x = 103692,
          y = 323578
        },
        {
          x = -13995,
          y = 225662
        },
        {
          x = -143361,
          y = -103287
        },
        {
          x = -373662,
          y = -483836
        },
      },
      offramps = {  }
    },
    {
      name = "R3E",
      cad = 1800,
      speed = 236.1,
      fls = { 9449, 10668, 11887 },
      types = { "B_737", "A_320", "B_757", "A_330" },
      fixes = {
        {
          x = 194762,
          y = 254762
        },
        {
          x = 23580,
          y = 426304
        },
        {
          x = -60333,
          y = 741947
        },
        {
          x = -63406,
          y = 857834
        },
        {
          x = -67407,
          y = 1069860
        },
      },
      offramps = {
        {
          p = 0.2,
          trunc = 3,
          airdrome = 26,
          apos = {
            x = -51260,
            y = 705734
          },
          via = {
            x = -45000,
            y = 690000
          },
          viaAlt = 3000
        },
      }
    },
    {
      name = "R3W",
      cad = 2400,
      speed = 236.1,
      fls = { 9144, 10363, 11582 },
      types = { "B_737", "A_320", "B_757", "A_330" },
      fixes = {
        {
          x = -52593,
          y = 1070140
        },
        {
          x = -48594,
          y = 858166
        },
        {
          x = -45667,
          y = 744053
        },
        {
          x = 36420,
          y = 433696
        },
        {
          x = 205238,
          y = 265238
        },
      },
      offramps = {  }
    },
    {
      name = "C6E",
      cad = 1800,
      speed = 236.1,
      fls = { 9754, 10973, 12192 },
      types = { "B_737", "A_320", "B_757", "A_330" },
      fixes = {
        {
          x = 298489,
          y = 992748
        },
        {
          x = 58892,
          y = 1042675
        },
        {
          x = -150628,
          y = 1062619
        },
        {
          x = -350554,
          y = 1077613
        },
      },
      offramps = {  }
    },
    {
      name = "C6W",
      cad = 2400,
      speed = 236.1,
      fls = { 10058, 11278, 12497 },
      types = { "B_737", "A_320", "B_757", "A_330" },
      fixes = {
        {
          x = -349446,
          y = 1092387
        },
        {
          x = -149372,
          y = 1077381
        },
        {
          x = 61108,
          y = 1057325
        },
        {
          x = 301511,
          y = 1007252
        },
      },
      offramps = {  }
    },
  },
  hubs = {
    {
      name = "KTS",
      airdrome = 25,
      pos = {
        x = -284887,
        y = 683859
      },
      types = { "B_737", "A_320", "B_757", "A_330" },
      arrCad = 900,
      arrAlt = 4500,
      arrSpeed = 180.6,
      entries = {
        {
          x = -303000,
          y = 554000
        },
        {
          x = -239000,
          y = 549000
        },
      },
      depCad = 900,
      depTypes = { "A_320", "B_737" },
      deps = {
        {
          kind = "land",
          airdrome = 22,
          apos = {
            x = -355811,
            y = 617386
          },
          via = {
            x = -328785,
            y = 642715
          },
          viaAlt = 5500
        },
        {
          kind = "exit",
          to = {
            x = -362000,
            y = 968000
          },
          alt = 8000
        },
        {
          kind = "land",
          airdrome = 29,
          apos = {
            x = -315671,
            y = 896630
          },
          via = {
            x = -310367,
            y = 859972
          },
          viaAlt = 5500
        },
      }
    },
    {
      name = "TBS",
      airdrome = 29,
      pos = {
        x = -315671,
        y = 896630
      },
      types = { "B_737", "A_320", "B_757", "A_330" },
      depCad = 1800,
      depTypes = { "A_320", "B_737" },
      deps = {
        {
          kind = "exit",
          to = {
            x = -330000,
            y = -200000
          },
          alt = 8000
        },
      }
    },
    {
      name = "SOC",
      airdrome = 18,
      pos = {
        x = -164496,
        y = 462219
      },
      types = { "B_737", "A_320", "B_757", "A_330" },
      arrCad = 2400,
      arrAlt = 4500,
      arrSpeed = 180.6,
      entries = {
        {
          x = 250000,
          y = 390000
        },
        {
          x = -30000,
          y = 420000
        },
      }
    },
  },
  ga = {
    {
      name = "W",
      cad = 300,
      maxActive = 6,
      fields = {
        {
          airdrome = 25,
          pos = {
            x = -284887,
            y = 683859
          }
        },
        {
          airdrome = 23,
          pos = {
            x = -281782,
            y = 647279
          }
        },
        {
          airdrome = 24,
          pos = {
            x = -317962,
            y = 635633
          }
        },
        {
          airdrome = 22,
          pos = {
            x = -355811,
            y = 617386
          }
        },
        {
          airdrome = 20,
          pos = {
            x = -220592,
            y = 564392
          }
        },
      },
      box = { -335000, -240000, 555000, 690000 },
      altLo = 600,
      altHi = 2450
    },
    {
      name = "KW",
      cad = 300,
      maxActive = 6,
      fields = {
        {
          airdrome = 12,
          pos = {
            x = -5412,
            y = 243129
          }
        },
        {
          airdrome = 15,
          pos = {
            x = -6577,
            y = 294388
          }
        },
        {
          airdrome = 13,
          pos = {
            x = 11685,
            y = 367934
          }
        },
        {
          airdrome = 19,
          pos = {
            x = 7718,
            y = 387879
          }
        },
        {
          airdrome = 14,
          pos = {
            x = -40918,
            y = 279256
          }
        },
        {
          airdrome = 17,
          pos = {
            x = -50379,
            y = 298406
          }
        },
      },
      box = { -40000, 35000, 235000, 410000 },
      altLo = 600,
      altHi = 2000
    },
  },
  liveries = {
    A_320 = { "fly georgia", "air france", "emirates", "air berlin olt" },
    A_330 = { "aeroflot", "etihad", "iberia" },
    B_737 = { "airzena", "british airways", "finnair", "airbaltic", "ukraine airlines", "haribo" },
    B_747 = { "lh", "ai" },
    B_757 = { "easyjet", "swiss", "ba", "thomson" },
    Cessna_210N = { "muster", "v5-bug" }
  },
  fuel = {
    A_320 = 18000,
    A_330 = 80000,
    B_737 = 16068,
    B_747 = 130000,
    B_757 = 25000,
    Cessna_210N = 300
  }
}

-- ============================================================================
-- CivTraffic runtime engine (appended below a per-map CFG table).
-- Curated civilian air-traffic corridors: infinite, lightweight, randomized.
--   - divided-highway lanes (offsets pre-baked into CFG fixes)
--   - random FL from the lane's semicircular set, random type/livery per spawn
--   - off-ramp landers by probability, hub arrival/departure conveyors,
--     GA wander regions
--   - global MAX ACTIVE cap + F10 "Civ Traffic" menu (pause / density / status)
-- Pure mission-scripting API: no MIST/MOOSE, no io/lfs, no os.*.
-- REQUIREMENTS: Civil Aircraft Mod installed; CFG.country (default EGYPT)
-- must belong to the NEUTRAL coalition in the mission (ME: coalitions setup),
-- or spawns will join whichever coalition owns that country.
-- ============================================================================

local CT = {}
CT.cfg = CivTrafficCFG
CT.paused = false
CT.densityMul = 1.0          -- >1 = sparser (multiplies cadence)
CT.spawned = {}              -- name -> {dieAt=<time or nil>}
CT.counter = 0
CT.log = function(s) env.info("[CivTraffic] " .. s) end

local COUNTRY = country.id[CT.cfg.country or "EGYPT"]

-- ---------------------------------------------------------------- helpers --
local function dist(a, b)
  local dx, dy = b.x - a.x, b.y - a.y
  return math.sqrt(dx * dx + dy * dy)
end

local function routeLen(fixes)
  local d = 0
  for i = 1, #fixes - 1 do d = d + dist(fixes[i], fixes[i + 1]) end
  return d
end

local function pick(t) return t[math.random(#t)] end

local function aliveCount()
  local n = 0
  for name, rec in pairs(CT.spawned) do
    local g = Group.getByName(name)
    if g and g:isExist() and g:getSize() > 0 then
      n = n + 1
    else
      CT.spawned[name] = nil
    end
  end
  return n
end

local function reaper()
  local now = timer.getTime()
  for name, rec in pairs(CT.spawned) do
    if rec.dieAt and now >= rec.dieAt then
      local g = Group.getByName(name)
      if g and g:isExist() then pcall(function() g:destroy() end) end
      CT.spawned[name] = nil
    end
  end
  return now + 60
end

local function optionsTask()
  return {
    id = "ComboTask",
    params = { tasks = {
      { number = 1, auto = false, id = "WrappedAction", enabled = true,
        params = { action = { id = "Option", params = { name = 0, value = 4 } } } },  -- ROE weapon hold
      { number = 2, auto = false, id = "WrappedAction", enabled = true,
        params = { action = { id = "Option", params = { name = 1, value = 0 } } } },  -- no reaction to threat
    } },
  }
end

local function turningPoint(x, y, alt, speed, first)
  return {
    x = x, y = y, alt = alt, alt_type = "BARO",
    type = "Turning Point", action = "Turning Point", name = "",
    speed = speed, speed_locked = true, ETA = 0, ETA_locked = first or false,
    formation_template = "",
    task = first and optionsTask() or { id = "ComboTask", params = { tasks = {} } },
  }
end

local function landPoint(x, y, airdromeId, speed)
  return {
    x = x, y = y, alt = 0, alt_type = "BARO",
    type = "Land", action = "Landing", airdromeId = airdromeId, name = "",
    speed = speed, speed_locked = true, ETA = 0, ETA_locked = false,
    formation_template = "",
    task = { id = "ComboTask", params = { tasks = {} } },
  }
end

local function parkingPoint(x, y, airdromeId, speed)
  return {
    x = x, y = y, alt = 20, alt_type = "BARO",
    type = "TakeOffParking", action = "From Parking Area", airdromeId = airdromeId, name = "",
    speed = speed, speed_locked = true, ETA = 0, ETA_locked = true,
    formation_template = "",
    task = optionsTask(),
  }
end

-- spec = {name, ptype, points, alt, speed, dieAfter (nil = lander)}
local function addPlane(spec)
  CT.counter = CT.counter + 1
  local name = string.format("CT %s-%04d %s", spec.tag, CT.counter, spec.ptype)
  local livs = CT.cfg.liveries[spec.ptype]
  local unit = {
    type = spec.ptype, skill = "High", name = name .. "-1",
    x = spec.points[1].x, y = spec.points[1].y,
    alt = spec.points[1].alt, alt_type = "BARO",
    speed = spec.speed,
    heading = math.atan2(spec.points[2].y - spec.points[1].y,
                         spec.points[2].x - spec.points[1].x),
    onboard_num = string.format("%03d", math.random(10, 999)),
    payload = { pylons = {}, fuel = CT.cfg.fuel[spec.ptype] or 10000,
                flare = 0, chaff = 0, gun = 0 },
    civil_plane = true,
    callsign = { [1] = 1, [2] = 1, [3] = 1, name = "Enfield11" },
  }
  if livs then unit.livery_id = pick(livs) end
  local group = {
    name = name, task = "Transport", tasks = {},
    communication = true, frequency = 251, modulation = 0, radioSet = false,
    hidden = false, hiddenOnPlanner = false, hiddenOnMFD = false,
    uncontrolled = false, start_time = 0,
    x = spec.points[1].x, y = spec.points[1].y,
    units = { unit },
    route = { points = spec.points },
  }
  local ok, err = pcall(function()
    coalition.addGroup(COUNTRY, Group.Category.AIRPLANE, group)
  end)
  if ok then
    CT.spawned[name] = { dieAt = spec.dieAfter and (timer.getTime() + spec.dieAfter) or nil }
    -- addGroup can "succeed" without creating anything; verify shortly after
    timer.scheduleFunction(function()
      local g = Group.getByName(name)
      if not (g and g:isExist()) then
        CT.log("SPAWN SILENTLY REJECTED by DCS: " .. name)
        CT.spawned[name] = nil
      end
      return nil
    end, nil, timer.getTime() + 5)
  else
    CT.log("SPAWN FAILED " .. name .. ": " .. tostring(err))
  end
  return ok
end

-- ------------------------------------------------------------------ lanes --
local function spawnLaneFlight(lane)
  if aliveCount() >= (CT.cfg.maxActive or 40) then return false end
  local ptype = pick(lane.types)
  local alt = pick(lane.fls)
  -- off-ramp roll
  local ramp = nil
  for _, r in ipairs(lane.offramps or {}) do
    if math.random() < r.p then ramp = r break end
  end
  local pts = {}
  local last = ramp and ramp.trunc or #lane.fixes
  for i = 1, last do
    local f = lane.fixes[i]
    pts[#pts + 1] = turningPoint(f.x, f.y, alt, lane.speed, i == 1)
  end
  local dieAfter = nil
  if ramp then
    pts[#pts + 1] = turningPoint(ramp.via.x, ramp.via.y, ramp.viaAlt, 111)
    pts[#pts + 1] = landPoint(ramp.apos.x, ramp.apos.y, ramp.airdrome, 111)
    dieAfter = routeLen(lane.fixes) / lane.speed + 3600  -- stuck-lander cleanup
  else
    dieAfter = routeLen(lane.fixes) / lane.speed + 600
  end
  return addPlane { tag = lane.name, ptype = ptype, points = pts,
                    alt = alt, speed = lane.speed, dieAfter = dieAfter }
end

local function laneLoop(lane)
  if not CT.paused then spawnLaneFlight(lane) end
  local jitter = 0.75 + math.random() * 0.5
  return timer.getTime() + lane.cad * jitter * CT.densityMul
end

-- ------------------------------------------------------------------- hubs --
local function spawnArrival(hub)
  if aliveCount() >= (CT.cfg.maxActive or 40) then return end
  local e = pick(hub.entries)
  local ptype = pick(hub.types)
  local brg = math.atan2(hub.pos.y - e.y, hub.pos.x - e.x)
  local via = { x = hub.pos.x - math.cos(brg) * 33000,
                y = hub.pos.y - math.sin(brg) * 33000 }
  local pts = {
    turningPoint(e.x, e.y, hub.arrAlt, hub.arrSpeed, true),
    turningPoint(via.x, via.y, math.max(1200, hub.arrAlt - 2500), 125),
    landPoint(hub.pos.x, hub.pos.y, hub.airdrome, 111),
  }
  addPlane { tag = hub.name .. "-ARR", ptype = ptype, points = pts,
             alt = hub.arrAlt, speed = hub.arrSpeed, dieAfter = 5400 }
end

local function spawnDeparture(hub)
  if aliveCount() >= (CT.cfg.maxActive or 40) then return end
  local plan = pick(hub.deps)
  local ptype = pick(hub.depTypes or hub.types)
  local pts = { parkingPoint(hub.pos.x, hub.pos.y, hub.airdrome, 0) }
  if plan.kind == "land" then
    pts[#pts + 1] = turningPoint(plan.via.x, plan.via.y, plan.viaAlt or 5500, 194)
    pts[#pts + 1] = landPoint(plan.apos.x, plan.apos.y, plan.airdrome, 111)
    addPlane { tag = hub.name .. "-DEP", ptype = ptype, points = pts,
               alt = 20, speed = 0, dieAfter = 7200 }
  else
    pts[#pts + 1] = turningPoint(plan.to.x, plan.to.y, plan.alt or 8000, 222)
    local d = dist(hub.pos, plan.to)
    addPlane { tag = hub.name .. "-DEP", ptype = ptype, points = pts,
               alt = 20, speed = 0, dieAfter = d / 222 + 1800 }
  end
end

local function hubArrLoop(hub)
  if not CT.paused then spawnArrival(hub) end
  return timer.getTime() + hub.arrCad * (0.75 + math.random() * 0.5) * CT.densityMul
end

local function hubDepLoop(hub)
  if not CT.paused then spawnDeparture(hub) end
  return timer.getTime() + hub.depCad * (0.75 + math.random() * 0.5) * CT.densityMul
end

-- --------------------------------------------------------------------- GA --
local function gaAlive(region)
  local n = 0
  for name in pairs(CT.spawned) do
    if string.find(name, "CT " .. region.name .. "GA", 1, true) == 1 then
      local g = Group.getByName(name)
      if g and g:isExist() and g:getSize() > 0 then n = n + 1 end
    end
  end
  return n
end

local function spawnGA(region)
  if aliveCount() >= (CT.cfg.maxActive or 40) then return end
  if gaAlive(region) >= (region.maxActive or 6) then return end
  local b = region.box
  local function rp()
    return { x = b[1] + math.random() * (b[2] - b[1]),
             y = b[3] + math.random() * (b[4] - b[3]) }
  end
  local cruise = region.altLo + math.random() * (region.altHi - region.altLo)
  local speed = 55 + math.random() * 12
  local dest = pick(region.fields)
  local pts, tag
  if math.random() < 0.65 then                     -- airborne wanderer
    local p1 = rp()
    pts = { turningPoint(p1.x, p1.y, cruise, speed, true) }
    for _ = 1, 2 + math.random(2) do
      local p = rp()
      pts[#pts + 1] = turningPoint(p.x, p.y, cruise, speed)
    end
    if math.random() < 0.7 then
      pts[#pts + 1] = landPoint(dest.pos.x, dest.pos.y, dest.airdrome, 55)
    end
  else                                              -- ramp start hop
    local origin = pick(region.fields)
    pts = { parkingPoint(origin.pos.x, origin.pos.y, origin.airdrome, 0) }
    for _ = 1, 1 + math.random(2) do
      local p = rp()
      pts[#pts + 1] = turningPoint(p.x, p.y, cruise, speed)
    end
    if dest.airdrome == origin.airdrome then dest = pick(region.fields) end
    pts[#pts + 1] = landPoint(dest.pos.x, dest.pos.y, dest.airdrome, 55)
  end
  addPlane { tag = region.name .. "GA", ptype = "Cessna_210N", points = pts,
             alt = cruise, speed = speed, dieAfter = 5400 }
end

local function gaLoop(region)
  if not CT.paused then spawnGA(region) end
  return timer.getTime() + region.cad * (0.75 + math.random() * 0.5) * CT.densityMul
end

-- -------------------------------------------------------- heartbeat log --
-- No F10 menu by design: a fire-and-forget template (like the baked air
-- missions) - players cannot touch the traffic. Health goes to dcs.log.
local function heartbeat()
  CT.log(string.format("active=%d  spawnedTotal=%d", aliveCount(), CT.counter))
  return timer.getTime() + 120
end

-- ------------------------------------------------------------------ start --
local function start()
  math.random()  -- warm the RNG
  CT.densityMul = CT.cfg.density or 1.0  -- <1 = denser (baked per map, no UI)
  local t0 = timer.getTime()
  local stagger = 0
  for _, lane in ipairs(CT.cfg.lanes or {}) do
    -- seed: one flight already enroute feel -> first spawn almost immediately
    timer.scheduleFunction(function() return laneLoop(lane) end, nil,
                           t0 + 5 + stagger)
    stagger = stagger + 37
  end
  for _, hub in ipairs(CT.cfg.hubs or {}) do
    if hub.arrCad then
      timer.scheduleFunction(function() return hubArrLoop(hub) end, nil,
                             t0 + 20 + stagger)
    end
    if hub.depCad then
      timer.scheduleFunction(function() return hubDepLoop(hub) end, nil,
                             t0 + 40 + stagger)
    end
    stagger = stagger + 37
  end
  for _, region in ipairs(CT.cfg.ga or {}) do
    timer.scheduleFunction(function() return gaLoop(region) end, nil,
                           t0 + 15 + stagger)
    stagger = stagger + 23
  end
  timer.scheduleFunction(reaper, nil, t0 + 120)
  timer.scheduleFunction(heartbeat, nil, t0 + 120)
  CT.log(string.format("started: %d lanes, %d hubs, %d GA regions, cap %d",
                       #(CT.cfg.lanes or {}), #(CT.cfg.hubs or {}),
                       #(CT.cfg.ga or {}), CT.cfg.maxActive or 40))
end

start()
