-- ============================================================================
-- CivTraffic-Nevada.lua - custom civilian air traffic for the Nevada map
-- Curated real-world corridors, infinite runtime spawning, F10-controllable.
-- INSTALL: Mission Editor -> new trigger: MISSION START -> DO SCRIPT FILE ->
--          this file. Requires: Civil Aircraft Mod installed; country EGYPT
--          placed in the NEUTRALS coalition (ME coalition setup).
-- Generated by gen_civtraffic_lua.py - edit the CFG table freely.
-- ============================================================================

CivTrafficCFG = {
  mapName = "Nevada",
  country = "EGYPT",
  maxActive = 60,
  density = 0.6,
  lanes = {
    {
      name = "N1E",
      cad = 900,
      speed = 236.1,
      fls = { 9449, 10668, 11887 },
      types = { "B_747", "A_330", "B_757", "B_737", "A_320" },
      fixes = {
        {
          x = -496207,
          y = -242286
        },
        {
          x = -456792,
          y = -77042
        },
        {
          x = -415830,
          y = -15429
        },
        {
          x = -305045,
          y = 105424
        },
        {
          x = -184598,
          y = 200808
        },
      },
      offramps = {
        {
          p = 0.25,
          trunc = 2,
          airdrome = 3,
          apos = {
            x = -416011,
            y = -26929
          },
          via = {
            x = -435000,
            y = -60000
          },
          viaAlt = 3300
        },
      }
    },
    {
      name = "N1W",
      cad = 1200,
      speed = 236.1,
      fls = { 9144, 10363, 11582 },
      types = { "B_747", "A_330", "B_757", "B_737", "A_320" },
      fixes = {
        {
          x = -175402,
          y = 189192
        },
        {
          x = -294955,
          y = 94576
        },
        {
          x = -404170,
          y = -24571
        },
        {
          x = -443208,
          y = -82958
        },
        {
          x = -481793,
          y = -245714
        },
      },
      offramps = {  }
    },
    {
      name = "N2E",
      cad = 1200,
      speed = 236.1,
      fls = { 10058, 11278, 12497 },
      types = { "B_737", "A_320", "B_757", "A_330" },
      fixes = {
        {
          x = -185149,
          y = -325326
        },
        {
          x = -335651,
          y = -179790
        },
        {
          x = -436567,
          y = -33429
        },
        {
          x = -496936,
          y = 127399
        },
      },
      offramps = {
        {
          p = 0.33,
          trunc = 3,
          airdrome = 3,
          apos = {
            x = -416011,
            y = -26929
          },
          via = {
            x = -425000,
            y = -50000
          },
          viaAlt = 3300
        },
      }
    },
    {
      name = "N2W",
      cad = 1800,
      speed = 236.1,
      fls = { 9754, 10973, 12192 },
      types = { "B_737", "A_320", "B_757", "A_330" },
      fixes = {
        {
          x = -483064,
          y = 132601
        },
        {
          x = -423433,
          y = -26571
        },
        {
          x = -324349,
          y = -170210
        },
        {
          x = -174851,
          y = -314674
        },
      },
      offramps = {  }
    },
    {
      name = "N3E",
      cad = 1500,
      speed = 236.1,
      fls = { 10058, 11278, 12497 },
      types = { "B_737", "A_320", "B_757", "A_330" },
      fixes = {
        {
          x = -493988,
          y = 157339
        },
        {
          x = -348831,
          y = 137315
        },
        {
          x = -183675,
          y = 107289
        },
      },
      offramps = {  }
    },
    {
      name = "N3W",
      cad = 2100,
      speed = 236.1,
      fls = { 9754, 10973, 12192 },
      types = { "B_737", "A_320", "B_757", "A_330" },
      fixes = {
        {
          x = -186325,
          y = 92711
        },
        {
          x = -351169,
          y = 122685
        },
        {
          x = -496012,
          y = 142661
        },
      },
      offramps = {  }
    },
  },
  hubs = {
    {
      name = "LAS",
      airdrome = 3,
      pos = {
        x = -416011,
        y = -26929
      },
      types = { "B_737", "A_320", "B_757", "A_330" },
      arrCad = 600,
      arrAlt = 5500,
      arrSpeed = 180.6,
      entries = {
        {
          x = -480000,
          y = -120000
        },
        {
          x = -330000,
          y = 80000
        },
      },
      depCad = 780,
      depTypes = { "A_320", "B_737" },
      deps = {
        {
          kind = "exit",
          to = {
            x = -180000,
            y = 195000
          },
          alt = 8000
        },
        {
          kind = "exit",
          to = {
            x = -489000,
            y = -244000
          },
          alt = 8000
        },
        {
          kind = "land",
          airdrome = 17,
          apos = {
            x = -197283,
            y = -201303
          },
          via = {
            x = -226246,
            y = -178213
          },
          viaAlt = 6000
        },
        {
          kind = "exit",
          to = {
            x = -490000,
            y = 130000
          },
          alt = 8000
        },
      }
    },
  },
  ga = {
    {
      name = "LV",
      cad = 300,
      maxActive = 7,
      fields = {
        {
          airdrome = 15,
          pos = {
            x = -400891,
            y = -31727
          }
        },
        {
          airdrome = 8,
          pos = {
            x = -427353,
            y = -25669
          }
        },
        {
          airdrome = 6,
          pos = {
            x = -429660,
            y = -1149
          }
        },
        {
          airdrome = 9,
          pos = {
            x = -450393,
            y = -43000
          }
        },
      },
      box = { -460000, -390000, -60000, 25000 },
      altLo = 1700,
      altHi = 2800
    },
    {
      name = "TOUR",
      cad = 300,
      maxActive = 7,
      fields = {
        {
          airdrome = 6,
          pos = {
            x = -429660,
            y = -1149
          }
        },
        {
          airdrome = 8,
          pos = {
            x = -427353,
            y = -25669
          }
        },
      },
      box = { -450000, -395000, -5000, 85000 },
      altLo = 1500,
      altHi = 2500
    },
  },
  liveries = {
    A_320 = { "fly georgia", "air france", "emirates", "air berlin olt" },
    A_330 = { "aeroflot", "etihad", "iberia" },
    B_737 = { "airzena", "british airways", "finnair", "airbaltic", "ukraine airlines", "haribo" },
    B_747 = { "lh", "ai" },
    B_757 = { "easyjet", "swiss", "ba", "thomson" },
    Cessna_210N = { "muster", "v5-bug" }
  },
  fuel = {
    A_320 = 18000,
    A_330 = 80000,
    B_737 = 16068,
    B_747 = 130000,
    B_757 = 25000,
    Cessna_210N = 300
  }
}

-- ============================================================================
-- CivTraffic runtime engine (appended below a per-map CFG table).
-- Curated civilian air-traffic corridors: infinite, lightweight, randomized.
--   - divided-highway lanes (offsets pre-baked into CFG fixes)
--   - random FL from the lane's semicircular set, random type/livery per spawn
--   - off-ramp landers by probability, hub arrival/departure conveyors,
--     GA wander regions
--   - global MAX ACTIVE cap + F10 "Civ Traffic" menu (pause / density / status)
-- Pure mission-scripting API: no MIST/MOOSE, no io/lfs, no os.*.
-- REQUIREMENTS: Civil Aircraft Mod installed; CFG.country (default EGYPT)
-- must belong to the NEUTRAL coalition in the mission (ME: coalitions setup),
-- or spawns will join whichever coalition owns that country.
-- ============================================================================

local CT = {}
CT.cfg = CivTrafficCFG
CT.paused = false
CT.densityMul = 1.0          -- >1 = sparser (multiplies cadence)
CT.spawned = {}              -- name -> {dieAt=<time or nil>}
CT.counter = 0
CT.log = function(s) env.info("[CivTraffic] " .. s) end

local COUNTRY = country.id[CT.cfg.country or "EGYPT"]

-- ---------------------------------------------------------------- helpers --
local function dist(a, b)
  local dx, dy = b.x - a.x, b.y - a.y
  return math.sqrt(dx * dx + dy * dy)
end

local function routeLen(fixes)
  local d = 0
  for i = 1, #fixes - 1 do d = d + dist(fixes[i], fixes[i + 1]) end
  return d
end

local function pick(t) return t[math.random(#t)] end

local function aliveCount()
  local n = 0
  for name, rec in pairs(CT.spawned) do
    local g = Group.getByName(name)
    if g and g:isExist() and g:getSize() > 0 then
      n = n + 1
    else
      CT.spawned[name] = nil
    end
  end
  return n
end

local function reaper()
  local now = timer.getTime()
  for name, rec in pairs(CT.spawned) do
    if rec.dieAt and now >= rec.dieAt then
      local g = Group.getByName(name)
      if g and g:isExist() then pcall(function() g:destroy() end) end
      CT.spawned[name] = nil
    end
  end
  return now + 60
end

local function optionsTask()
  return {
    id = "ComboTask",
    params = { tasks = {
      { number = 1, auto = false, id = "WrappedAction", enabled = true,
        params = { action = { id = "Option", params = { name = 0, value = 4 } } } },  -- ROE weapon hold
      { number = 2, auto = false, id = "WrappedAction", enabled = true,
        params = { action = { id = "Option", params = { name = 1, value = 0 } } } },  -- no reaction to threat
    } },
  }
end

local function turningPoint(x, y, alt, speed, first)
  return {
    x = x, y = y, alt = alt, alt_type = "BARO",
    type = "Turning Point", action = "Turning Point", name = "",
    speed = speed, speed_locked = true, ETA = 0, ETA_locked = first or false,
    formation_template = "",
    task = first and optionsTask() or { id = "ComboTask", params = { tasks = {} } },
  }
end

local function landPoint(x, y, airdromeId, speed)
  return {
    x = x, y = y, alt = 0, alt_type = "BARO",
    type = "Land", action = "Landing", airdromeId = airdromeId, name = "",
    speed = speed, speed_locked = true, ETA = 0, ETA_locked = false,
    formation_template = "",
    task = { id = "ComboTask", params = { tasks = {} } },
  }
end

local function parkingPoint(x, y, airdromeId, speed)
  return {
    x = x, y = y, alt = 20, alt_type = "BARO",
    type = "TakeOffParking", action = "From Parking Area", airdromeId = airdromeId, name = "",
    speed = speed, speed_locked = true, ETA = 0, ETA_locked = true,
    formation_template = "",
    task = optionsTask(),
  }
end

-- spec = {name, ptype, points, alt, speed, dieAfter (nil = lander)}
local function addPlane(spec)
  CT.counter = CT.counter + 1
  local name = string.format("CT %s-%04d %s", spec.tag, CT.counter, spec.ptype)
  local livs = CT.cfg.liveries[spec.ptype]
  local unit = {
    type = spec.ptype, skill = "High", name = name .. "-1",
    x = spec.points[1].x, y = spec.points[1].y,
    alt = spec.points[1].alt, alt_type = "BARO",
    speed = spec.speed,
    heading = math.atan2(spec.points[2].y - spec.points[1].y,
                         spec.points[2].x - spec.points[1].x),
    onboard_num = string.format("%03d", math.random(10, 999)),
    payload = { pylons = {}, fuel = CT.cfg.fuel[spec.ptype] or 10000,
                flare = 0, chaff = 0, gun = 0 },
    civil_plane = true,
    callsign = { [1] = 1, [2] = 1, [3] = 1, name = "Enfield11" },
  }
  if livs then unit.livery_id = pick(livs) end
  local group = {
    name = name, task = "Transport", tasks = {},
    communication = true, frequency = 251, modulation = 0, radioSet = false,
    hidden = false, hiddenOnPlanner = false, hiddenOnMFD = false,
    uncontrolled = false, start_time = 0,
    x = spec.points[1].x, y = spec.points[1].y,
    units = { unit },
    route = { points = spec.points },
  }
  local ok, err = pcall(function()
    coalition.addGroup(COUNTRY, Group.Category.AIRPLANE, group)
  end)
  if ok then
    CT.spawned[name] = { dieAt = spec.dieAfter and (timer.getTime() + spec.dieAfter) or nil }
    -- addGroup can "succeed" without creating anything; verify shortly after
    timer.scheduleFunction(function()
      local g = Group.getByName(name)
      if not (g and g:isExist()) then
        CT.log("SPAWN SILENTLY REJECTED by DCS: " .. name)
        CT.spawned[name] = nil
      end
      return nil
    end, nil, timer.getTime() + 5)
  else
    CT.log("SPAWN FAILED " .. name .. ": " .. tostring(err))
  end
  return ok
end

-- ------------------------------------------------------------------ lanes --
local function spawnLaneFlight(lane)
  if aliveCount() >= (CT.cfg.maxActive or 40) then return false end
  local ptype = pick(lane.types)
  local alt = pick(lane.fls)
  -- off-ramp roll
  local ramp = nil
  for _, r in ipairs(lane.offramps or {}) do
    if math.random() < r.p then ramp = r break end
  end
  local pts = {}
  local last = ramp and ramp.trunc or #lane.fixes
  for i = 1, last do
    local f = lane.fixes[i]
    pts[#pts + 1] = turningPoint(f.x, f.y, alt, lane.speed, i == 1)
  end
  local dieAfter = nil
  if ramp then
    pts[#pts + 1] = turningPoint(ramp.via.x, ramp.via.y, ramp.viaAlt, 111)
    pts[#pts + 1] = landPoint(ramp.apos.x, ramp.apos.y, ramp.airdrome, 111)
    dieAfter = routeLen(lane.fixes) / lane.speed + 3600  -- stuck-lander cleanup
  else
    dieAfter = routeLen(lane.fixes) / lane.speed + 600
  end
  return addPlane { tag = lane.name, ptype = ptype, points = pts,
                    alt = alt, speed = lane.speed, dieAfter = dieAfter }
end

local function laneLoop(lane)
  if not CT.paused then spawnLaneFlight(lane) end
  local jitter = 0.75 + math.random() * 0.5
  return timer.getTime() + lane.cad * jitter * CT.densityMul
end

-- ------------------------------------------------------------------- hubs --
local function spawnArrival(hub)
  if aliveCount() >= (CT.cfg.maxActive or 40) then return end
  local e = pick(hub.entries)
  local ptype = pick(hub.types)
  local brg = math.atan2(hub.pos.y - e.y, hub.pos.x - e.x)
  local via = { x = hub.pos.x - math.cos(brg) * 33000,
                y = hub.pos.y - math.sin(brg) * 33000 }
  local pts = {
    turningPoint(e.x, e.y, hub.arrAlt, hub.arrSpeed, true),
    turningPoint(via.x, via.y, math.max(1200, hub.arrAlt - 2500), 125),
    landPoint(hub.pos.x, hub.pos.y, hub.airdrome, 111),
  }
  addPlane { tag = hub.name .. "-ARR", ptype = ptype, points = pts,
             alt = hub.arrAlt, speed = hub.arrSpeed, dieAfter = 5400 }
end

local function spawnDeparture(hub)
  if aliveCount() >= (CT.cfg.maxActive or 40) then return end
  local plan = pick(hub.deps)
  local ptype = pick(hub.depTypes or hub.types)
  local pts = { parkingPoint(hub.pos.x, hub.pos.y, hub.airdrome, 0) }
  if plan.kind == "land" then
    pts[#pts + 1] = turningPoint(plan.via.x, plan.via.y, plan.viaAlt or 5500, 194)
    pts[#pts + 1] = landPoint(plan.apos.x, plan.apos.y, plan.airdrome, 111)
    addPlane { tag = hub.name .. "-DEP", ptype = ptype, points = pts,
               alt = 20, speed = 0, dieAfter = 7200 }
  else
    pts[#pts + 1] = turningPoint(plan.to.x, plan.to.y, plan.alt or 8000, 222)
    local d = dist(hub.pos, plan.to)
    addPlane { tag = hub.name .. "-DEP", ptype = ptype, points = pts,
               alt = 20, speed = 0, dieAfter = d / 222 + 1800 }
  end
end

local function hubArrLoop(hub)
  if not CT.paused then spawnArrival(hub) end
  return timer.getTime() + hub.arrCad * (0.75 + math.random() * 0.5) * CT.densityMul
end

local function hubDepLoop(hub)
  if not CT.paused then spawnDeparture(hub) end
  return timer.getTime() + hub.depCad * (0.75 + math.random() * 0.5) * CT.densityMul
end

-- --------------------------------------------------------------------- GA --
local function gaAlive(region)
  local n = 0
  for name in pairs(CT.spawned) do
    if string.find(name, "CT " .. region.name .. "GA", 1, true) == 1 then
      local g = Group.getByName(name)
      if g and g:isExist() and g:getSize() > 0 then n = n + 1 end
    end
  end
  return n
end

local function spawnGA(region)
  -- GA gets headroom equal to its own cap ON TOP of the global cap: airliners
  -- saturating maxActive must never starve the low-level GA layer (these are
  -- the aircraft players are sent up to visually identify).
  if aliveCount() >= (CT.cfg.maxActive or 40) + (region.maxActive or 6) then return end
  if gaAlive(region) >= (region.maxActive or 6) then return end
  local b = region.box
  local function rp()
    return { x = b[1] + math.random() * (b[2] - b[1]),
             y = b[3] + math.random() * (b[4] - b[3]) }
  end
  local cruise = region.altLo + math.random() * (region.altHi - region.altLo)
  local speed = 55 + math.random() * 12
  local dest = pick(region.fields)
  local pts, tag
  if math.random() < 0.65 then                     -- airborne wanderer
    local p1 = rp()
    pts = { turningPoint(p1.x, p1.y, cruise, speed, true) }
    for _ = 1, 2 + math.random(2) do
      local p = rp()
      pts[#pts + 1] = turningPoint(p.x, p.y, cruise, speed)
    end
    if math.random() < 0.7 then
      pts[#pts + 1] = landPoint(dest.pos.x, dest.pos.y, dest.airdrome, 55)
    end
  else                                              -- ramp start hop
    local origin = pick(region.fields)
    pts = { parkingPoint(origin.pos.x, origin.pos.y, origin.airdrome, 0) }
    for _ = 1, 1 + math.random(2) do
      local p = rp()
      pts[#pts + 1] = turningPoint(p.x, p.y, cruise, speed)
    end
    if dest.airdrome == origin.airdrome then dest = pick(region.fields) end
    pts[#pts + 1] = landPoint(dest.pos.x, dest.pos.y, dest.airdrome, 55)
  end
  addPlane { tag = region.name .. "GA", ptype = "Cessna_210N", points = pts,
             alt = cruise, speed = speed, dieAfter = 5400 }
end

local function gaLoop(region)
  if not CT.paused then spawnGA(region) end
  return timer.getTime() + region.cad * (0.75 + math.random() * 0.5) * CT.densityMul
end

-- -------------------------------------------------------- heartbeat log --
local function heartbeat()
  CT.log(string.format("active=%d  spawnedTotal=%d", aliveCount(), CT.counter))
  return timer.getTime() + 120
end

-- ---------------------------------------------------------- F10 control --
-- "Civ Traffic" menu (cfg.f10menu ~= false): host can pause / clear /
-- resume / re-density the ambient air traffic mid-mission.
local function removeAll()
  for name in pairs(CT.spawned) do
    local g = Group.getByName(name)
    if g and g:isExist() then pcall(function() g:destroy() end) end
    CT.spawned[name] = nil
  end
end

local function buildMenu()
  if CT.cfg.f10menu == false then return end
  local root = missionCommands.addSubMenu("Civ Traffic")
  missionCommands.addCommand("Status", root, function()
    trigger.action.outText(string.format(
      "Civ Traffic: %d aircraft | %s | density x%.2g",
      aliveCount(), CT.paused and "PAUSED" or "running", 1 / CT.densityMul), 15)
  end)
  missionCommands.addCommand("Turn OFF (stop + clear all)", root, function()
    CT.paused = true; removeAll()
    trigger.action.outText("Civ Traffic: OFF - all aircraft removed, spawning stopped", 12)
  end)
  missionCommands.addCommand("Turn ON (resume spawning)", root, function()
    CT.paused = false
    trigger.action.outText("Civ Traffic: ON - spawning resumed", 10)
  end)
  local den = missionCommands.addSubMenu("Density", root)
  missionCommands.addCommand("Low", den, function()
    CT.densityMul = math.max(1.4, (CT.cfg.density or 1.0) * 2)
    trigger.action.outText("Civ Traffic density: LOW", 10)
  end)
  missionCommands.addCommand("Normal", den, function()
    CT.densityMul = CT.cfg.density or 1.0
    trigger.action.outText("Civ Traffic density: NORMAL", 10)
  end)
  missionCommands.addCommand("High", den, function()
    CT.densityMul = (CT.cfg.density or 1.0) * 0.6
    trigger.action.outText("Civ Traffic density: HIGH", 10)
  end)
end

-- ------------------------------------------------------------------ start --
local function start()
  math.random()  -- warm the RNG
  CT.densityMul = CT.cfg.density or 1.0  -- <1 = denser (baked per map, no UI)
  local t0 = timer.getTime()
  local stagger = 0
  for _, lane in ipairs(CT.cfg.lanes or {}) do
    -- seed: one flight already enroute feel -> first spawn almost immediately
    timer.scheduleFunction(function() return laneLoop(lane) end, nil,
                           t0 + 5 + stagger)
    stagger = stagger + 37
  end
  for _, hub in ipairs(CT.cfg.hubs or {}) do
    if hub.arrCad then
      timer.scheduleFunction(function() return hubArrLoop(hub) end, nil,
                             t0 + 20 + stagger)
    end
    if hub.depCad then
      timer.scheduleFunction(function() return hubDepLoop(hub) end, nil,
                             t0 + 40 + stagger)
    end
    stagger = stagger + 37
  end
  for _, region in ipairs(CT.cfg.ga or {}) do
    timer.scheduleFunction(function() return gaLoop(region) end, nil,
                           t0 + 15 + stagger)
    stagger = stagger + 23
  end
  timer.scheduleFunction(reaper, nil, t0 + 120)
  timer.scheduleFunction(heartbeat, nil, t0 + 120)
  buildMenu()
  CT.log(string.format("started: %d lanes, %d hubs, %d GA regions, cap %d",
                       #(CT.cfg.lanes or {}), #(CT.cfg.hubs or {}),
                       #(CT.cfg.ga or {}), CT.cfg.maxActive or 40))
end

start()
