-- ============================================================================
-- CivTraffic-MarianaIslands.lua - custom civilian air traffic for the MarianaIslands map
-- Curated real-world corridors, infinite runtime spawning, F10-controllable.
-- INSTALL: Mission Editor -> new trigger: MISSION START -> DO SCRIPT FILE ->
--          this file. Requires: Civil Aircraft Mod installed; country EGYPT
--          placed in the NEUTRALS coalition (ME coalition setup).
-- Generated by gen_civtraffic_lua.py - edit the CFG table freely.
-- ============================================================================

CivTrafficCFG = {
  mapName = "MarianaIslands",
  country = "EGYPT",
  maxActive = 25,
  lanes = {
    {
      name = "M1E",
      cad = 1500,
      speed = 236.1,
      fls = { 9449, 10668, 11887 },
      types = { "B_747", "A_330", "B_757", "B_737", "A_320" },
      fixes = {
        {
          x = 281885,
          y = 122836
        },
        {
          x = 187668,
          y = 98089
        },
        {
          x = 63716,
          y = 33591
        },
        {
          x = -7127,
          y = -11828
        },
        {
          x = -248345,
          y = -67221
        },
      },
      offramps = {
        {
          p = 0.25,
          trunc = 2,
          airdrome = 2,
          apos = {
            x = 180035,
            y = 101856
          },
          via = {
            x = 172000,
            y = 95000
          },
          viaAlt = 2500
        },
        {
          p = 0.25,
          trunc = 4,
          airdrome = 4,
          apos = {
            x = -24,
            y = -78
          },
          via = {
            x = 15000,
            y = 15000
          },
          viaAlt = 2800
        },
      }
    },
    {
      name = "M1W",
      cad = 2100,
      speed = 236.1,
      fls = { 9144, 10363, 11582 },
      types = { "B_747", "A_330", "B_757", "B_737", "A_320" },
      fixes = {
        {
          x = -251655,
          y = -52779
        },
        {
          x = -12873,
          y = 1828
        },
        {
          x = 56284,
          y = 46409
        },
        {
          x = 182332,
          y = 111911
        },
        {
          x = 278115,
          y = 137164
        },
      },
      offramps = {  }
    },
    {
      name = "M2E",
      cad = 1800,
      speed = 236.1,
      fls = { 10058, 11278, 12497 },
      types = { "B_747", "A_330", "B_757", "B_737", "A_320" },
      fixes = {
        {
          x = 92621,
          y = -600656
        },
        {
          x = 52623,
          y = -150679
        },
        {
          x = 32612,
          y = 59459
        },
        {
          x = 12602,
          y = 449621
        },
      },
      offramps = {  }
    },
    {
      name = "M2W",
      cad = 2400,
      speed = 236.1,
      fls = { 9754, 10973, 12192 },
      types = { "B_747", "A_330", "B_757", "B_737", "A_320" },
      fixes = {
        {
          x = 27398,
          y = 450379
        },
        {
          x = 47388,
          y = 60541
        },
        {
          x = 67377,
          y = -149321
        },
        {
          x = 107379,
          y = -599344
        },
      },
      offramps = {  }
    },
  },
  hubs = {
    {
      name = "GUM",
      airdrome = 4,
      pos = {
        x = -24,
        y = -78
      },
      types = { "B_747", "A_330", "B_757", "B_737", "A_320" },
      arrCad = 1100,
      arrAlt = 4500,
      arrSpeed = 180.6,
      entries = {
        {
          x = 200000,
          y = 30000
        },
        {
          x = -60000,
          y = -200000
        },
      },
      depCad = 1100,
      depTypes = { "A_320", "B_737" },
      deps = {
        {
          kind = "land",
          airdrome = 2,
          apos = {
            x = 180035,
            y = 101856
          },
          via = {
            x = 147802,
            y = 83608
          },
          viaAlt = 5500
        },
        {
          kind = "exit",
          to = {
            x = -250000,
            y = -60000
          },
          alt = 8000
        },
        {
          kind = "exit",
          to = {
            x = 100000,
            y = -600000
          },
          alt = 8000
        },
      }
    },
  },
  ga = {
    {
      name = "MI",
      cad = 300,
      maxActive = 6,
      fields = {
        {
          airdrome = 1,
          pos = {
            x = 75885,
            y = 48590
          }
        },
        {
          airdrome = 2,
          pos = {
            x = 180035,
            y = 101856
          }
        },
        {
          airdrome = 3,
          pos = {
            x = 166860,
            y = 89957
          }
        },
        {
          airdrome = 4,
          pos = {
            x = -24,
            y = -78
          }
        },
      },
      box = { -30000, 200000, -30000, 130000 },
      altLo = 600,
      altHi = 2000
    },
  },
  liveries = {
    A_320 = { "fly georgia", "air france", "emirates", "air berlin olt" },
    A_330 = { "aeroflot", "etihad", "iberia" },
    B_737 = { "airzena", "british airways", "finnair", "airbaltic", "ukraine airlines", "haribo" },
    B_747 = { "lh", "ai" },
    B_757 = { "easyjet", "swiss", "ba", "thomson" },
    Cessna_210N = { "muster", "v5-bug" }
  },
  fuel = {
    A_320 = 18000,
    A_330 = 80000,
    B_737 = 16068,
    B_747 = 130000,
    B_757 = 25000,
    Cessna_210N = 300
  }
}

-- ============================================================================
-- CivTraffic runtime engine (appended below a per-map CFG table).
-- Curated civilian air-traffic corridors: infinite, lightweight, randomized.
--   - divided-highway lanes (offsets pre-baked into CFG fixes)
--   - random FL from the lane's semicircular set, random type/livery per spawn
--   - off-ramp landers by probability, hub arrival/departure conveyors,
--     GA wander regions
--   - global MAX ACTIVE cap + F10 "Civ Traffic" menu (pause / density / status)
-- Pure mission-scripting API: no MIST/MOOSE, no io/lfs, no os.*.
-- REQUIREMENTS: Civil Aircraft Mod installed; CFG.country (default EGYPT)
-- must belong to the NEUTRAL coalition in the mission (ME: coalitions setup),
-- or spawns will join whichever coalition owns that country.
-- ============================================================================

local CT = {}
CT.cfg = CivTrafficCFG
CT.paused = false
CT.densityMul = 1.0          -- >1 = sparser (multiplies cadence)
CT.spawned = {}              -- name -> {dieAt=<time or nil>}
CT.counter = 0
CT.log = function(s) env.info("[CivTraffic] " .. s) end

local COUNTRY = country.id[CT.cfg.country or "EGYPT"]

-- ---------------------------------------------------------------- helpers --
local function dist(a, b)
  local dx, dy = b.x - a.x, b.y - a.y
  return math.sqrt(dx * dx + dy * dy)
end

local function routeLen(fixes)
  local d = 0
  for i = 1, #fixes - 1 do d = d + dist(fixes[i], fixes[i + 1]) end
  return d
end

local function pick(t) return t[math.random(#t)] end

local function aliveCount()
  local n = 0
  for name, rec in pairs(CT.spawned) do
    local g = Group.getByName(name)
    if g and g:isExist() and g:getSize() > 0 then
      n = n + 1
    else
      CT.spawned[name] = nil
    end
  end
  return n
end

local function reaper()
  local now = timer.getTime()
  for name, rec in pairs(CT.spawned) do
    if rec.dieAt and now >= rec.dieAt then
      local g = Group.getByName(name)
      if g and g:isExist() then pcall(function() g:destroy() end) end
      CT.spawned[name] = nil
    end
  end
  return now + 60
end

local function optionsTask()
  return {
    id = "ComboTask",
    params = { tasks = {
      { number = 1, auto = false, id = "WrappedAction", enabled = true,
        params = { action = { id = "Option", params = { name = 0, value = 4 } } } },  -- ROE weapon hold
      { number = 2, auto = false, id = "WrappedAction", enabled = true,
        params = { action = { id = "Option", params = { name = 1, value = 0 } } } },  -- no reaction to threat
    } },
  }
end

local function turningPoint(x, y, alt, speed, first)
  return {
    x = x, y = y, alt = alt, alt_type = "BARO",
    type = "Turning Point", action = "Turning Point",
    speed = speed, speed_locked = true, ETA = 0, ETA_locked = first or false,
    formation_template = "",
    task = first and optionsTask() or { id = "ComboTask", params = { tasks = {} } },
  }
end

local function landPoint(x, y, airdromeId, speed)
  return {
    x = x, y = y, alt = 0, alt_type = "BARO",
    type = "Land", action = "Landing", airdromeId = airdromeId,
    speed = speed, speed_locked = true, ETA = 0, ETA_locked = false,
    formation_template = "",
    task = { id = "ComboTask", params = { tasks = {} } },
  }
end

local function parkingPoint(x, y, airdromeId, speed)
  return {
    x = x, y = y, alt = 20, alt_type = "BARO",
    type = "TakeOffParking", action = "From Parking Area", airdromeId = airdromeId,
    speed = speed, speed_locked = true, ETA = 0, ETA_locked = true,
    formation_template = "",
    task = optionsTask(),
  }
end

-- spec = {name, ptype, points, alt, speed, dieAfter (nil = lander)}
local function addPlane(spec)
  CT.counter = CT.counter + 1
  local name = string.format("CT %s-%04d %s", spec.tag, CT.counter, spec.ptype)
  local livs = CT.cfg.liveries[spec.ptype]
  local unit = {
    type = spec.ptype, skill = "High", name = name .. "-1",
    x = spec.points[1].x, y = spec.points[1].y,
    alt = spec.points[1].alt, alt_type = "BARO",
    speed = spec.speed,
    heading = math.atan2(spec.points[2].y - spec.points[1].y,
                         spec.points[2].x - spec.points[1].x),
    onboard_num = string.format("%03d", math.random(10, 999)),
    payload = { pylons = {}, fuel = CT.cfg.fuel[spec.ptype] or 10000,
                flare = 0, chaff = 0, gun = 0 },
    civil_plane = true,
    callsign = { [1] = 1, [2] = 1, [3] = 1, name = "Enfield11" },
  }
  if livs then unit.livery_id = pick(livs) end
  local group = {
    name = name, task = "Transport",
    communication = true, frequency = 251, modulation = 0,
    x = spec.points[1].x, y = spec.points[1].y,
    units = { unit },
    route = { points = spec.points },
  }
  local ok, err = pcall(function()
    coalition.addGroup(COUNTRY, Group.Category.AIRPLANE, group)
  end)
  if ok then
    CT.spawned[name] = { dieAt = spec.dieAfter and (timer.getTime() + spec.dieAfter) or nil }
  else
    CT.log("SPAWN FAILED " .. name .. ": " .. tostring(err))
  end
  return ok
end

-- ------------------------------------------------------------------ lanes --
local function spawnLaneFlight(lane)
  if aliveCount() >= (CT.cfg.maxActive or 40) then return false end
  local ptype = pick(lane.types)
  local alt = pick(lane.fls)
  -- off-ramp roll
  local ramp = nil
  for _, r in ipairs(lane.offramps or {}) do
    if math.random() < r.p then ramp = r break end
  end
  local pts = {}
  local last = ramp and ramp.trunc or #lane.fixes
  for i = 1, last do
    local f = lane.fixes[i]
    pts[#pts + 1] = turningPoint(f.x, f.y, alt, lane.speed, i == 1)
  end
  local dieAfter = nil
  if ramp then
    pts[#pts + 1] = turningPoint(ramp.via.x, ramp.via.y, ramp.viaAlt, 111)
    pts[#pts + 1] = landPoint(ramp.apos.x, ramp.apos.y, ramp.airdrome, 111)
    dieAfter = routeLen(lane.fixes) / lane.speed + 3600  -- stuck-lander cleanup
  else
    dieAfter = routeLen(lane.fixes) / lane.speed + 600
  end
  return addPlane { tag = lane.name, ptype = ptype, points = pts,
                    alt = alt, speed = lane.speed, dieAfter = dieAfter }
end

local function laneLoop(lane)
  if not CT.paused then spawnLaneFlight(lane) end
  local jitter = 0.75 + math.random() * 0.5
  return timer.getTime() + lane.cad * jitter * CT.densityMul
end

-- ------------------------------------------------------------------- hubs --
local function spawnArrival(hub)
  if aliveCount() >= (CT.cfg.maxActive or 40) then return end
  local e = pick(hub.entries)
  local ptype = pick(hub.types)
  local brg = math.atan2(hub.pos.y - e.y, hub.pos.x - e.x)
  local via = { x = hub.pos.x - math.cos(brg) * 33000,
                y = hub.pos.y - math.sin(brg) * 33000 }
  local pts = {
    turningPoint(e.x, e.y, hub.arrAlt, hub.arrSpeed, true),
    turningPoint(via.x, via.y, math.max(1200, hub.arrAlt - 2500), 125),
    landPoint(hub.pos.x, hub.pos.y, hub.airdrome, 111),
  }
  addPlane { tag = hub.name .. "-ARR", ptype = ptype, points = pts,
             alt = hub.arrAlt, speed = hub.arrSpeed, dieAfter = 5400 }
end

local function spawnDeparture(hub)
  if aliveCount() >= (CT.cfg.maxActive or 40) then return end
  local plan = pick(hub.deps)
  local ptype = pick(hub.depTypes or hub.types)
  local pts = { parkingPoint(hub.pos.x, hub.pos.y, hub.airdrome, 0) }
  if plan.kind == "land" then
    pts[#pts + 1] = turningPoint(plan.via.x, plan.via.y, plan.viaAlt or 5500, 194)
    pts[#pts + 1] = landPoint(plan.apos.x, plan.apos.y, plan.airdrome, 111)
    addPlane { tag = hub.name .. "-DEP", ptype = ptype, points = pts,
               alt = 20, speed = 0, dieAfter = 7200 }
  else
    pts[#pts + 1] = turningPoint(plan.to.x, plan.to.y, plan.alt or 8000, 222)
    local d = dist(hub.pos, plan.to)
    addPlane { tag = hub.name .. "-DEP", ptype = ptype, points = pts,
               alt = 20, speed = 0, dieAfter = d / 222 + 1800 }
  end
end

local function hubArrLoop(hub)
  if not CT.paused then spawnArrival(hub) end
  return timer.getTime() + hub.arrCad * (0.75 + math.random() * 0.5) * CT.densityMul
end

local function hubDepLoop(hub)
  if not CT.paused then spawnDeparture(hub) end
  return timer.getTime() + hub.depCad * (0.75 + math.random() * 0.5) * CT.densityMul
end

-- --------------------------------------------------------------------- GA --
local function gaAlive(region)
  local n = 0
  for name in pairs(CT.spawned) do
    if string.find(name, "CT " .. region.name .. "GA", 1, true) == 1 then
      local g = Group.getByName(name)
      if g and g:isExist() and g:getSize() > 0 then n = n + 1 end
    end
  end
  return n
end

local function spawnGA(region)
  if aliveCount() >= (CT.cfg.maxActive or 40) then return end
  if gaAlive(region) >= (region.maxActive or 6) then return end
  local b = region.box
  local function rp()
    return { x = b[1] + math.random() * (b[2] - b[1]),
             y = b[3] + math.random() * (b[4] - b[3]) }
  end
  local cruise = region.altLo + math.random() * (region.altHi - region.altLo)
  local speed = 55 + math.random() * 12
  local dest = pick(region.fields)
  local pts, tag
  if math.random() < 0.65 then                     -- airborne wanderer
    local p1 = rp()
    pts = { turningPoint(p1.x, p1.y, cruise, speed, true) }
    for _ = 1, 2 + math.random(2) do
      local p = rp()
      pts[#pts + 1] = turningPoint(p.x, p.y, cruise, speed)
    end
    if math.random() < 0.7 then
      pts[#pts + 1] = landPoint(dest.pos.x, dest.pos.y, dest.airdrome, 55)
    end
  else                                              -- ramp start hop
    local origin = pick(region.fields)
    pts = { parkingPoint(origin.pos.x, origin.pos.y, origin.airdrome, 0) }
    for _ = 1, 1 + math.random(2) do
      local p = rp()
      pts[#pts + 1] = turningPoint(p.x, p.y, cruise, speed)
    end
    if dest.airdrome == origin.airdrome then dest = pick(region.fields) end
    pts[#pts + 1] = landPoint(dest.pos.x, dest.pos.y, dest.airdrome, 55)
  end
  addPlane { tag = region.name .. "GA", ptype = "Cessna_210N", points = pts,
             alt = cruise, speed = speed, dieAfter = 5400 }
end

local function gaLoop(region)
  if not CT.paused then spawnGA(region) end
  return timer.getTime() + region.cad * (0.75 + math.random() * 0.5) * CT.densityMul
end

-- -------------------------------------------------------------- F10 menu --
local function buildMenu()
  local root = missionCommands.addSubMenu("Civ Traffic")
  missionCommands.addCommand("Status", root, function()
    trigger.action.outText(string.format(
      "CivTraffic: %d aircraft active | paused=%s | density x%.2g",
      aliveCount(), tostring(CT.paused), 1 / CT.densityMul), 15)
  end)
  missionCommands.addCommand("Pause spawning", root, function()
    CT.paused = true
    trigger.action.outText("CivTraffic: spawning PAUSED (aircraft aloft continue)", 10)
  end)
  missionCommands.addCommand("Resume spawning", root, function()
    CT.paused = false
    trigger.action.outText("CivTraffic: spawning RESUMED", 10)
  end)
  missionCommands.addCommand("Density: low", root, function()
    CT.densityMul = 2.0
    trigger.action.outText("CivTraffic density: LOW (half rate)", 10)
  end)
  missionCommands.addCommand("Density: normal", root, function()
    CT.densityMul = 1.0
    trigger.action.outText("CivTraffic density: NORMAL", 10)
  end)
  missionCommands.addCommand("Density: high", root, function()
    CT.densityMul = 0.6
    trigger.action.outText("CivTraffic density: HIGH", 10)
  end)
end

-- ------------------------------------------------------------------ start --
local function start()
  math.random()  -- warm the RNG
  local t0 = timer.getTime()
  local stagger = 0
  for _, lane in ipairs(CT.cfg.lanes or {}) do
    -- seed: one flight already enroute feel -> first spawn almost immediately
    timer.scheduleFunction(function() return laneLoop(lane) end, nil,
                           t0 + 5 + stagger)
    stagger = stagger + 37
  end
  for _, hub in ipairs(CT.cfg.hubs or {}) do
    if hub.arrCad then
      timer.scheduleFunction(function() return hubArrLoop(hub) end, nil,
                             t0 + 20 + stagger)
    end
    if hub.depCad then
      timer.scheduleFunction(function() return hubDepLoop(hub) end, nil,
                             t0 + 40 + stagger)
    end
    stagger = stagger + 37
  end
  for _, region in ipairs(CT.cfg.ga or {}) do
    timer.scheduleFunction(function() return gaLoop(region) end, nil,
                           t0 + 15 + stagger)
    stagger = stagger + 23
  end
  timer.scheduleFunction(reaper, nil, t0 + 120)
  buildMenu()
  CT.log(string.format("started: %d lanes, %d hubs, %d GA regions, cap %d",
                       #(CT.cfg.lanes or {}), #(CT.cfg.hubs or {}),
                       #(CT.cfg.ga or {}), CT.cfg.maxActive or 40))
  trigger.action.outText("CivTraffic " .. (CT.cfg.mapName or "") ..
                         " running - F10 menu: Civ Traffic", 15)
end

start()
