-- ============================================================================
-- ShipTraffic-MarianaIslands.lua - civilian shipping traffic for the MarianaIslands map
-- Real-world lanes (TSS-style one-way pairs), anchorage queues at ports,
-- fishing fleets. Stock DCS ships - NO MODS REQUIRED.
-- INSTALL: Mission Editor -> trigger: MISSION START -> DO SCRIPT FILE ->
--          this file. Country EGYPT must be in the NEUTRALS coalition.
-- Generated by gen_shiptraffic_lua.py - edit the CFG table freely.
-- ============================================================================

ShipTrafficCFG = {
  mapName = "MarianaIslands",
  country = "EGYPT",
  maxActive = 16,
  lanes = {
    {
      name = "MB1A",
      cad = 2400,
      speed = 8,
      types = { "Dry-cargo ship-1", "Dry-cargo ship-2", "HandyWind", "ELNYA" },
      seed = 3,
      fixes = {
        {
          x = 250222,
          y = -92769
        },
        {
          x = 222,
          y = -112769
        },
        {
          x = -249778,
          y = -132769
        },
      },
      anchors = {  }
    },
    {
      name = "MB1B",
      cad = 2400,
      speed = 8,
      types = { "Dry-cargo ship-1", "Dry-cargo ship-2", "HandyWind", "ELNYA" },
      seed = 3,
      fixes = {
        {
          x = -250222,
          y = -127231
        },
        {
          x = -222,
          y = -107231
        },
        {
          x = 249778,
          y = -87231
        },
      },
      anchors = {  }
    },
    {
      name = "MB2A",
      cad = 2700,
      speed = 8,
      types = { "Dry-cargo ship-1", "Dry-cargo ship-2", "HandyWind", "ELNYA" },
      seed = 3,
      fixes = {
        {
          x = -72770,
          y = -449790
        },
        {
          x = -47663,
          y = -119209
        },
        {
          x = -2435,
          y = -36664
        },
      },
      anchors = {
        {
          p = 0.6,
          trunc = 3,
          pos = {
            x = 4000,
            y = -28000
          }
        },
      }
    },
    {
      name = "MB2B",
      cad = 3000,
      speed = 8,
      types = { "Dry-cargo ship-1", "Dry-cargo ship-2", "HandyWind", "ELNYA" },
      seed = 2,
      fixes = {
        {
          x = 2435,
          y = -39336
        },
        {
          x = -42337,
          y = -120791
        },
        {
          x = -67230,
          y = -450210
        },
      },
      anchors = {  }
    },
  },
  fishing = {
    {
      name = "CHNF",
      box = { 60000, 175000, 20000, 60000 },
      types = { "ZWEZDNY" },
      maxActive = 4,
      cad = 900
    },
    {
      name = "GUMF",
      box = { -60000, -25000, -40000, 20000 },
      types = { "ZWEZDNY" },
      maxActive = 3,
      cad = 1000
    },
  }
}

-- ============================================================================
-- ShipTraffic runtime engine (appended below a per-map ShipTrafficCFG table).
-- Curated civilian SHIPPING lanes: pre-seeded along their length at mission
-- start (ships are slow - the sea must start populated), slow trickle of new
-- hulls at the lane entries, anchorage off-ramps at ports, port departure
-- lanes, fishing/pleasure wander regions. Stock DCS ships - no mods needed.
--   - one-way lanes (TSS-style offsets pre-baked into CFG fixes)
--   - global MAX ACTIVE cap + F10 "Ship Traffic" menu
-- Pure mission-scripting API: no MIST/MOOSE, no io/lfs, no os.*.
-- REQUIREMENT: CFG.country (default EGYPT) must be in the NEUTRALS coalition.
-- ============================================================================

local ST = {}
ST.cfg = ShipTrafficCFG
ST.paused = false
ST.densityMul = 1.0
ST.spawned = {}
ST.counter = 0
ST.log = function(s) env.info("[ShipTraffic] " .. s) end

local COUNTRY = country.id[ST.cfg.country or "EGYPT"]

-- ---------------------------------------------------------------- helpers --
local function dist(a, b)
  local dx, dy = b.x - a.x, b.y - a.y
  return math.sqrt(dx * dx + dy * dy)
end

local function routeLen(fixes, fromIdx)
  local d = 0
  for i = (fromIdx or 1), #fixes - 1 do d = d + dist(fixes[i], fixes[i + 1]) end
  return d
end

local function pick(t) return t[math.random(#t)] end

-- position `d` meters along a fix list; returns point and index of NEXT fix
local function pointAlong(fixes, d)
  local remaining = d
  for i = 1, #fixes - 1 do
    local seg = dist(fixes[i], fixes[i + 1])
    if remaining <= seg then
      local f = remaining / seg
      return { x = fixes[i].x + f * (fixes[i + 1].x - fixes[i].x),
               y = fixes[i].y + f * (fixes[i + 1].y - fixes[i].y) }, i + 1
    end
    remaining = remaining - seg
  end
  return { x = fixes[#fixes].x, y = fixes[#fixes].y }, #fixes
end

local function aliveCount()
  local n = 0
  for name in pairs(ST.spawned) do
    local g = Group.getByName(name)
    if g and g:isExist() and g:getSize() > 0 then
      n = n + 1
    else
      ST.spawned[name] = nil
    end
  end
  return n
end

local function reaper()
  local now = timer.getTime()
  for name, rec in pairs(ST.spawned) do
    if rec.dieAt and now >= rec.dieAt then
      local g = Group.getByName(name)
      if g and g:isExist() then pcall(function() g:destroy() end) end
      ST.spawned[name] = nil
    end
  end
  return now + 90
end

local function shipPoint(x, y, speed, first)
  local task = { id = "ComboTask", params = { tasks = {} } }
  if first then
    task = { id = "ComboTask", params = { tasks = {
      { number = 1, auto = false, id = "WrappedAction", enabled = true,
        params = { action = { id = "Option",
                              params = { name = 0, value = 4 } } } },  -- ROE weapon hold
    } } }
  end
  return { x = x, y = y, alt = 0, alt_type = "BARO",
           type = "Turning Point", action = "Turning Point",
           speed = speed, speed_locked = true, ETA = 0,
           ETA_locked = first or false, formation_template = "", task = task }
end

local function addShip(spec)
  ST.counter = ST.counter + 1
  local name = string.format("ST %s-%04d", spec.tag, ST.counter)
  local hdg = 0
  if spec.points[2] then
    hdg = math.atan2(spec.points[2].y - spec.points[1].y,
                     spec.points[2].x - spec.points[1].x)
  end
  local group = {
    name = name, task = "Transport",
    x = spec.points[1].x, y = spec.points[1].y,
    units = { { type = spec.stype, name = name .. "-1", skill = "Average",
                x = spec.points[1].x, y = spec.points[1].y,
                heading = hdg, transportable = { randomTransportable = false } } },
    route = { points = spec.points },
  }
  local ok, err = pcall(function()
    coalition.addGroup(COUNTRY, Group.Category.SHIP, group)
  end)
  if ok then
    ST.spawned[name] = { dieAt = spec.dieAfter and (timer.getTime() + spec.dieAfter) or nil }
  else
    ST.log("SPAWN FAILED " .. name .. ": " .. tostring(err))
  end
  return ok
end

-- ------------------------------------------------------------------ lanes --
-- build a route from a lane starting at fraction f (0 = entry), honoring an
-- optional anchorage diversion roll
local function laneRoute(lane, frac)
  local total = routeLen(lane.fixes)
  local start, nextIdx = pointAlong(lane.fixes, frac * total)
  -- small perpendicular scatter so seeded ships aren't a perfect conga line
  start.x = start.x + (math.random() - 0.5) * 1500
  start.y = start.y + (math.random() - 0.5) * 1500
  local anchor = nil
  for _, a in ipairs(lane.anchors or {}) do
    if math.random() < a.p and nextIdx <= a.trunc then anchor = a break end
  end
  local pts = { shipPoint(start.x, start.y, lane.speed, true) }
  local last = anchor and anchor.trunc or #lane.fixes
  for i = nextIdx, last do
    pts[#pts + 1] = shipPoint(lane.fixes[i].x, lane.fixes[i].y, lane.speed)
  end
  local sailLen = routeLen(lane.fixes, nextIdx) + dist(start, lane.fixes[math.min(nextIdx, #lane.fixes)])
  local dieAfter
  if anchor then
    pts[#pts + 1] = shipPoint(anchor.pos.x, anchor.pos.y, lane.speed * 0.6)
    dieAfter = sailLen / lane.speed + 3600 + math.random(3600)  -- ride at anchor
  else
    dieAfter = sailLen / lane.speed + 1800
  end
  return pts, dieAfter
end

local function spawnLaneShip(lane, frac)
  if aliveCount() >= (ST.cfg.maxActive or 25) then return false end
  local pts, dieAfter = laneRoute(lane, frac)
  return addShip { tag = lane.name, stype = pick(lane.types),
                   points = pts, dieAfter = dieAfter }
end

local function laneLoop(lane)
  if not ST.paused then spawnLaneShip(lane, 0) end
  local jitter = 0.7 + math.random() * 0.6
  return timer.getTime() + lane.cad * jitter * ST.densityMul
end

-- ---------------------------------------------------------------- fishing --
local function fleetAlive(region)
  local n = 0
  for name in pairs(ST.spawned) do
    if string.find(name, "ST " .. region.name, 1, true) == 1 then
      local g = Group.getByName(name)
      if g and g:isExist() and g:getSize() > 0 then n = n + 1 end
    end
  end
  return n
end

local function spawnFisher(region)
  if aliveCount() >= (ST.cfg.maxActive or 25) then return end
  if fleetAlive(region) >= (region.maxActive or 4) then return end
  local b = region.box
  local function rp()
    return { x = b[1] + math.random() * (b[2] - b[1]),
             y = b[3] + math.random() * (b[4] - b[3]) }
  end
  local speed = 3 + math.random() * 4
  local p1 = rp()
  local pts = { shipPoint(p1.x, p1.y, speed, true) }
  for _ = 1, 2 + math.random(2) do
    local p = rp()
    pts[#pts + 1] = shipPoint(p.x, p.y, speed)
  end
  addShip { tag = region.name, stype = pick(region.types),
            points = pts, dieAfter = 5400 + math.random(3600) }
end

local function fisherLoop(region)
  if not ST.paused then spawnFisher(region) end
  return timer.getTime() + region.cad * (0.7 + math.random() * 0.6) * ST.densityMul
end

-- -------------------------------------------------------------- F10 menu --
local function buildMenu()
  local root = missionCommands.addSubMenu("Ship Traffic")
  missionCommands.addCommand("Status", root, function()
    trigger.action.outText(string.format(
      "ShipTraffic: %d vessels active | paused=%s | density x%.2g",
      aliveCount(), tostring(ST.paused), 1 / ST.densityMul), 15)
  end)
  missionCommands.addCommand("Pause spawning", root, function()
    ST.paused = true
    trigger.action.outText("ShipTraffic: spawning PAUSED (vessels underway continue)", 10)
  end)
  missionCommands.addCommand("Resume spawning", root, function()
    ST.paused = false
    trigger.action.outText("ShipTraffic: spawning RESUMED", 10)
  end)
  missionCommands.addCommand("Density: low", root, function()
    ST.densityMul = 2.0
    trigger.action.outText("ShipTraffic density: LOW", 10)
  end)
  missionCommands.addCommand("Density: normal", root, function()
    ST.densityMul = 1.0
    trigger.action.outText("ShipTraffic density: NORMAL", 10)
  end)
  missionCommands.addCommand("Density: high", root, function()
    ST.densityMul = 0.6
    trigger.action.outText("ShipTraffic density: HIGH", 10)
  end)
end

-- ------------------------------------------------------------------ start --
local function start()
  math.random()
  local t0 = timer.getTime()
  local stagger = 0
  for _, lane in ipairs(ST.cfg.lanes or {}) do
    -- pre-seed the lane: ships already distributed along it at mission start
    for s = 1, (lane.seed or 0) do
      local frac = (s - 0.5 + (math.random() - 0.5) * 0.6) / (lane.seed)
      timer.scheduleFunction(function()
        spawnLaneShip(lane, math.max(0.02, math.min(0.95, frac)))
        return nil
      end, nil, t0 + 3 + stagger + s * 4)
    end
    timer.scheduleFunction(function() return laneLoop(lane) end, nil,
                           t0 + 60 + stagger)
    stagger = stagger + 17
  end
  for _, region in ipairs(ST.cfg.fishing or {}) do
    -- seed half the fleet immediately
    for s = 1, math.floor((region.maxActive or 4) / 2) do
      timer.scheduleFunction(function() spawnFisher(region) return nil end,
                             nil, t0 + 10 + stagger + s * 5)
    end
    timer.scheduleFunction(function() return fisherLoop(region) end, nil,
                           t0 + 45 + stagger)
    stagger = stagger + 13
  end
  timer.scheduleFunction(reaper, nil, t0 + 180)
  buildMenu()
  ST.log(string.format("started: %d lanes, %d fishing regions, cap %d",
                       #(ST.cfg.lanes or {}), #(ST.cfg.fishing or {}),
                       ST.cfg.maxActive or 25))
  trigger.action.outText("ShipTraffic " .. (ST.cfg.mapName or "") ..
                         " running - F10 menu: Ship Traffic", 15)
end

start()
