-- ============================================================================
-- ShipTraffic-Kola.lua - civilian shipping traffic for the Kola map
-- Real-world lanes (TSS-style one-way pairs), anchorage queues at ports,
-- fishing fleets. Stock DCS ships - NO MODS REQUIRED.
-- INSTALL: Mission Editor -> trigger: MISSION START -> DO SCRIPT FILE ->
--          this file. Country EGYPT must be in the NEUTRALS coalition.
-- Generated by gen_shiptraffic_lua.py - edit the CFG table freely.
-- ============================================================================

ShipTrafficCFG = {
  mapName = "Kola",
  country = "EGYPT",
  maxActive = 24,
  lanes = {
    {
      name = "KB1A",
      cad = 3000,
      speed = 8,
      types = { "Dry-cargo ship-1", "Dry-cargo ship-2", "HandyWind", "ELNYA" },
      seed = 5,
      fixes = {
        {
          x = 317227,
          y = 59837
        },
        {
          x = 297225,
          y = 399861
        },
        {
          x = 287224,
          y = 639884
        },
      },
      anchors = {
        {
          p = 0.6,
          trunc = 2,
          pos = {
            x = 262000,
            y = 415000
          }
        },
      }
    },
    {
      name = "KB1B",
      cad = 3600,
      speed = 8,
      types = { "Dry-cargo ship-1", "Dry-cargo ship-2", "HandyWind", "ELNYA" },
      seed = 3,
      fixes = {
        {
          x = 292776,
          y = 640116
        },
        {
          x = 302775,
          y = 400139
        },
        {
          x = 322773,
          y = 60163
        },
      },
      anchors = {  }
    },
    {
      name = "KB2A",
      cad = 3600,
      speed = 9,
      types = { "Dry-cargo ship-1", "Dry-cargo ship-2", "HandyWind" },
      seed = 5,
      fixes = {
        {
          x = -42394,
          y = -418591
        },
        {
          x = 57573,
          y = -248648
        },
        {
          x = 157445,
          y = -58910
        },
        {
          x = 237365,
          y = 180878
        },
      },
      anchors = {
        {
          p = 0.4,
          trunc = 4,
          pos = {
            x = 238000,
            y = 272000
          }
        },
      }
    },
    {
      name = "KB2B",
      cad = 3600,
      speed = 9,
      types = { "Dry-cargo ship-1", "Dry-cargo ship-2", "HandyWind" },
      seed = 3,
      fixes = {
        {
          x = 242635,
          y = 179122
        },
        {
          x = 162555,
          y = -61090
        },
        {
          x = 62427,
          y = -251352
        },
        {
          x = -37606,
          y = -421409
        },
      },
      anchors = {  }
    },
  },
  fishing = {
    {
      name = "BARF",
      box = { 280000, 340000, 150000, 350000 },
      types = { "ZWEZDNY" },
      maxActive = 7,
      cad = 900
    },
  }
}

-- ============================================================================
-- ShipTraffic runtime engine (appended below a per-map ShipTrafficCFG table).
-- Curated civilian SHIPPING lanes: pre-seeded along their length at mission
-- start (ships are slow - the sea must start populated), slow trickle of new
-- hulls at the lane entries, anchorage off-ramps at ports, port departure
-- lanes, fishing/pleasure wander regions. Stock DCS ships - no mods needed.
--   - one-way lanes (TSS-style offsets pre-baked into CFG fixes)
--   - global MAX ACTIVE cap + F10 "Ship Traffic" menu
-- Pure mission-scripting API: no MIST/MOOSE, no io/lfs, no os.*.
-- REQUIREMENT: CFG.country (default EGYPT) must be in the NEUTRALS coalition.
-- ============================================================================

local ST = {}
ST.cfg = ShipTrafficCFG
ST.paused = false
ST.densityMul = 1.0
ST.spawned = {}
ST.counter = 0
ST.log = function(s) env.info("[ShipTraffic] " .. s) end

local COUNTRY = country.id[ST.cfg.country or "EGYPT"]

-- ---------------------------------------------------------------- helpers --
local function dist(a, b)
  local dx, dy = b.x - a.x, b.y - a.y
  return math.sqrt(dx * dx + dy * dy)
end

local function routeLen(fixes, fromIdx)
  local d = 0
  for i = (fromIdx or 1), #fixes - 1 do d = d + dist(fixes[i], fixes[i + 1]) end
  return d
end

local function pick(t) return t[math.random(#t)] end

-- ---- WATER GATE: never spawn / route a ship onto land -----------------
-- DCS land.getSurfaceType returns 1=LAND 2=SHALLOW_WATER 3=WATER 4=ROAD
-- 5=RUNWAY. Hand-drawn lanes can't be verified offline (no coastline data in
-- the generator), so the ENGINE rejects definite-land points. FAIL-OPEN: we
-- blacklist only LAND/ROAD/RUNWAY and allow everything else (incl. a failed
-- API call or an enum we don't recognise) - a broken check must never be able
-- to zero out all traffic. Better a rare stray hull than an empty sea.
local NOTWATER = { [1] = true, [4] = true, [5] = true }  -- LAND, ROAD, RUNWAY
if land and land.SurfaceType then
  NOTWATER = {
    [land.SurfaceType.LAND] = true,
    [land.SurfaceType.ROAD] = true,
    [land.SurfaceType.RUNWAY] = true,
  }
end
ST.landRejects = 0

local function isWater(p)
  if not (land and land.getSurfaceType) then return true end  -- API absent: allow
  local ok, st = pcall(land.getSurfaceType, { x = p.x, y = p.y })
  if not ok then return true end               -- call failed: allow (fail-open)
  return NOTWATER[st] ~= true                   -- reject only definite land
end

-- ---- ROUTE REPAIR --------------------------------------------------------
-- Rejecting bad routes isn't enough: hand-drawn lanes can't be verified
-- offline, so in fjord terrain (Kola) most candidate legs clip land and we'd
-- either reject nearly everything or let a hull sail into a headland. Instead
-- the engine REPAIRS a route at runtime, where the land data actually lives:
--   * sample every leg finely (islands/inlets can be well under 1 km),
--   * if a leg crosses land, search perpendicular for a water DETOUR,
--   * if no detour exists, TRUNCATE at the last reachable point.
-- Result: waypoints and the legs between them are never over land.
local SAMPLE_M = 600
local MAX_SAMPLES = 60

local function legIsWater(a, b)
  if not isWater(a) or not isWater(b) then return false end
  local d = dist(a, b)
  local steps = math.floor(d / SAMPLE_M)
  if steps > MAX_SAMPLES then steps = MAX_SAMPLES end
  for s = 1, steps do
    local f = s / (steps + 1)
    if not isWater({ x = a.x + (b.x - a.x) * f,
                     y = a.y + (b.y - a.y) * f }) then
      return false
    end
  end
  return true
end

-- perpendicular search for a mid-waypoint that gets a->b around the obstacle
local DETOURS = { 2500, 5000, 9000, 15000, 24000, 36000 }
local function findDetour(a, b)
  local dx, dy = b.x - a.x, b.y - a.y
  local L = math.sqrt(dx * dx + dy * dy)
  if L < 1 then return nil end
  local nx, ny = -dy / L, dx / L                 -- unit normal to the leg
  local mx, my = (a.x + b.x) / 2, (a.y + b.y) / 2
  for _, off in ipairs(DETOURS) do
    for _, sgn in ipairs({ 1, -1 }) do
      local p = { x = mx + nx * off * sgn, y = my + ny * off * sgn }
      if isWater(p) and legIsWater(a, p) and legIsWater(p, b) then
        return p
      end
    end
  end
  return nil
end

-- pts: shipPoint tables. Returns a repaired list (>=1 pt) or nil if the
-- spawn point itself is on land. `mk(x,y)` builds a new intermediate point.
local function repairRoute(pts, mk)
  if #pts == 0 or not isWater(pts[1]) then return nil end
  local out = { pts[1] }
  for i = 2, #pts do
    local a, b = out[#out], pts[i]
    if legIsWater(a, b) then
      out[#out + 1] = b
    else
      local d = findDetour(a, b)
      if d then
        out[#out + 1] = mk(d.x, d.y)
        out[#out + 1] = b
        ST.detours = (ST.detours or 0) + 1
      else
        break                       -- truncate: rest of the route is unreachable
      end
    end
  end
  return out
end

-- position `d` meters along a fix list; returns point and index of NEXT fix
local function pointAlong(fixes, d)
  local remaining = d
  for i = 1, #fixes - 1 do
    local seg = dist(fixes[i], fixes[i + 1])
    if remaining <= seg then
      local f = remaining / seg
      return { x = fixes[i].x + f * (fixes[i + 1].x - fixes[i].x),
               y = fixes[i].y + f * (fixes[i + 1].y - fixes[i].y) }, i + 1
    end
    remaining = remaining - seg
  end
  return { x = fixes[#fixes].x, y = fixes[#fixes].y }, #fixes
end

local function aliveCount()
  local n = 0
  for name in pairs(ST.spawned) do
    local g = Group.getByName(name)
    if g and g:isExist() and g:getSize() > 0 then
      n = n + 1
    else
      ST.spawned[name] = nil
    end
  end
  return n
end

local function reaper()
  local now = timer.getTime()
  for name, rec in pairs(ST.spawned) do
    if rec.dieAt and now >= rec.dieAt then
      local g = Group.getByName(name)
      if g and g:isExist() then pcall(function() g:destroy() end) end
      ST.spawned[name] = nil
    end
  end
  return now + 90
end

local function shipPoint(x, y, speed, first)
  local task = { id = "ComboTask", params = { tasks = {} } }
  if first then
    task = { id = "ComboTask", params = { tasks = {
      { number = 1, auto = false, id = "WrappedAction", enabled = true,
        params = { action = { id = "Option",
                              params = { name = 0, value = 4 } } } },  -- ROE weapon hold
    } } }
  end
  return { x = x, y = y, alt = 0, alt_type = "BARO",
           type = "Turning Point", action = "Turning Point", name = "",
           speed = speed, speed_locked = true, ETA = 0,
           ETA_locked = first or false, formation_template = "", task = task }
end

local function addShip(spec)
  ST.counter = ST.counter + 1
  local name = string.format("ST %s-%04d", spec.tag, ST.counter)
  local hdg = 0
  if spec.points[2] then
    hdg = math.atan2(spec.points[2].y - spec.points[1].y,
                     spec.points[2].x - spec.points[1].x)
  end
  -- group shape mirrors an ME-placed naval group exactly (coalition.addGroup
  -- rejects malformed tables SILENTLY - no error, no unit; v1 shipped a
  -- plane-style table with task="Transport" and no frequency, hence no boats)
  local group = {
    name = name, visible = false, taskSelected = true, tasks = {},
    hidden = false, hiddenOnPlanner = false, hiddenOnMFD = false,
    start_time = 0,
    x = spec.points[1].x, y = spec.points[1].y,
    units = { { type = spec.stype, name = name .. "-1", skill = "Average",
                x = spec.points[1].x, y = spec.points[1].y,
                heading = hdg, frequency = 127500000 } },
    route = { points = spec.points },
  }
  local ok, err = pcall(function()
    coalition.addGroup(COUNTRY, Group.Category.SHIP, group)
  end)
  if ok then
    ST.spawned[name] = { dieAt = spec.dieAfter and (timer.getTime() + spec.dieAfter) or nil }
    -- addGroup can "succeed" without creating anything; verify shortly after
    timer.scheduleFunction(function()
      local g = Group.getByName(name)
      if not (g and g:isExist()) then
        ST.log("SPAWN SILENTLY REJECTED by DCS: " .. name)
        ST.spawned[name] = nil
      end
      return nil
    end, nil, timer.getTime() + 5)
  else
    ST.log("SPAWN FAILED " .. name .. ": " .. tostring(err))
  end
  return ok
end

-- ------------------------------------------------------------------ lanes --
-- build a route from a lane starting at fraction f (0 = entry), honoring an
-- optional anchorage diversion roll
local function laneRoute(lane, frac)
  local total = routeLen(lane.fixes)
  local start, nextIdx = pointAlong(lane.fixes, frac * total)
  -- small perpendicular scatter so seeded ships aren't a perfect conga line
  start.x = start.x + (math.random() - 0.5) * 1500
  start.y = start.y + (math.random() - 0.5) * 1500
  local anchor = nil
  for _, a in ipairs(lane.anchors or {}) do
    if math.random() < a.p and nextIdx <= a.trunc then anchor = a break end
  end
  local pts = { shipPoint(start.x, start.y, lane.speed, true) }
  local last = anchor and anchor.trunc or #lane.fixes
  for i = nextIdx, last do
    pts[#pts + 1] = shipPoint(lane.fixes[i].x, lane.fixes[i].y, lane.speed)
  end
  local sailLen = routeLen(lane.fixes, nextIdx) + dist(start, lane.fixes[math.min(nextIdx, #lane.fixes)])
  local dieAfter
  if anchor then
    pts[#pts + 1] = shipPoint(anchor.pos.x, anchor.pos.y, lane.speed * 0.6)
    dieAfter = sailLen / lane.speed + 3600 + math.random(3600)  -- ride at anchor
  else
    dieAfter = sailLen / lane.speed + 1800
  end
  return pts, dieAfter
end

local MIN_VOYAGE_M = 12000   -- a hull with nowhere to go isn't worth spawning

local function spawnLaneShip(lane, frac)
  if aliveCount() >= (ST.cfg.maxActive or 25) then return false end
  local pts, dieAfter = laneRoute(lane, frac)
  -- repair rather than reject: detour around land, truncate what's unreachable
  local fixed = repairRoute(pts, function(x, y)
    return shipPoint(x, y, lane.speed)
  end)
  if not fixed or #fixed < 2 then
    ST.landRejects = ST.landRejects + 1
    return false
  end
  local voyage = 0
  for i = 1, #fixed - 1 do voyage = voyage + dist(fixed[i], fixed[i + 1]) end
  if voyage < MIN_VOYAGE_M then
    ST.landRejects = ST.landRejects + 1
    return false
  end
  -- route was shortened: retime the cleanup so it isn't reaped mid-voyage
  dieAfter = voyage / lane.speed + 1800
  return addShip { tag = lane.name, stype = pick(lane.types),
                   points = fixed, dieAfter = dieAfter }
end

-- seeding wants a RELIABLE placement near `frac`: a single land-reject would
-- silently drop a seeded ship (why Hormuz showed ~9 of 12). Retry with small
-- frac jitter so the seed count actually lands on water.
local function seedLaneShip(lane, frac)
  for attempt = 1, 10 do
    local f = math.max(0.02, math.min(0.97, frac + (math.random() - 0.5) * 0.08 * attempt))
    if spawnLaneShip(lane, f) then return true end
    if aliveCount() >= (ST.cfg.maxActive or 25) then return false end  -- cap, not land
  end
  return false
end

local function laneLoop(lane)
  if not ST.paused then spawnLaneShip(lane, 0) end
  local jitter = 0.7 + math.random() * 0.6
  return timer.getTime() + lane.cad * jitter * ST.densityMul
end

-- ---------------------------------------------------------------- fishing --
local function fleetAlive(region)
  local n = 0
  for name in pairs(ST.spawned) do
    if string.find(name, "ST " .. region.name, 1, true) == 1 then
      local g = Group.getByName(name)
      if g and g:isExist() and g:getSize() > 0 then n = n + 1 end
    end
  end
  return n
end

local function spawnFisher(region)
  if aliveCount() >= (ST.cfg.maxActive or 25) then return end
  if fleetAlive(region) >= (region.maxActive or 4) then return end
  local b = region.box
  -- random point that is ON WATER (retry a few times; give up if the box is
  -- mostly land so we never beach a trawler)
  local function waterPoint()
    for _ = 1, 10 do
      local p = { x = b[1] + math.random() * (b[2] - b[1]),
                  y = b[3] + math.random() * (b[4] - b[3]) }
      if isWater(p) then return p end
    end
    return nil
  end
  local speed = 3 + math.random() * 4
  local p1 = waterPoint()
  if not p1 then ST.landRejects = ST.landRejects + 1; return end
  local pts = { shipPoint(p1.x, p1.y, speed, true) }
  -- inshore trawlers work right against the coast, so each hop must be a
  -- clear water LEG, not just two water endpoints with a headland between
  for _ = 1, 2 + math.random(2) do
    for _ = 1, 6 do
      local p = waterPoint()
      if p and legIsWater(pts[#pts], p) then
        pts[#pts + 1] = shipPoint(p.x, p.y, speed)
        break
      end
    end
  end
  if #pts < 2 then ST.landRejects = ST.landRejects + 1; return end
  addShip { tag = region.name, stype = pick(region.types),
            points = pts, dieAfter = 5400 + math.random(3600) }
end

local function fisherLoop(region)
  if not ST.paused then spawnFisher(region) end
  return timer.getTime() + region.cad * (0.7 + math.random() * 0.6) * ST.densityMul
end

-- ------------------------------------------------------------- top-up ----
-- Awkward coastlines (Kola's fjords) make the repair reject a lot of
-- candidate routes, which would leave the sea thin. Periodically top the
-- fleet back up toward the cap by seeding at random points along random
-- lanes, so density self-heals no matter how hostile the terrain is.
local function topUp()
  local lanes = ST.cfg.lanes or {}
  if not ST.paused and #lanes > 0 then
    local cap = ST.cfg.maxActive or 25
    local tries = 0
    while aliveCount() < cap and tries < 12 do
      tries = tries + 1
      seedLaneShip(pick(lanes), 0.05 + math.random() * 0.9)
    end
  end
  return timer.getTime() + 180
end

-- -------------------------------------------------------- heartbeat log --
-- No F10 menu by design: this is a fire-and-forget template (like the baked
-- air missions) - players cannot touch the traffic. Health is logged to
-- dcs.log periodically so it stays diagnosable without any in-game UI.
local function heartbeat()
  ST.log(string.format("active=%d  spawnedTotal=%d  land-skips=%d  detours=%d",
                       aliveCount(), ST.counter, ST.landRejects, ST.detours or 0))
  return timer.getTime() + 120
end

-- ------------------------------------------------------------------ start --
local function start()
  math.random()
  local t0 = timer.getTime()
  local stagger = 0
  for _, lane in ipairs(ST.cfg.lanes or {}) do
    -- pre-seed the lane: ships already distributed along it at mission start
    for s = 1, (lane.seed or 0) do
      local frac = (s - 0.5 + (math.random() - 0.5) * 0.6) / (lane.seed)
      timer.scheduleFunction(function()
        seedLaneShip(lane, math.max(0.02, math.min(0.95, frac)))
        return nil
      end, nil, t0 + 3 + stagger + s * 4)
    end
    timer.scheduleFunction(function() return laneLoop(lane) end, nil,
                           t0 + 60 + stagger)
    stagger = stagger + 17
  end
  for _, region in ipairs(ST.cfg.fishing or {}) do
    -- seed half the fleet immediately
    for s = 1, math.floor((region.maxActive or 4) / 2) do
      timer.scheduleFunction(function() spawnFisher(region) return nil end,
                             nil, t0 + 10 + stagger + s * 5)
    end
    timer.scheduleFunction(function() return fisherLoop(region) end, nil,
                           t0 + 45 + stagger)
    stagger = stagger + 13
  end
  timer.scheduleFunction(reaper, nil, t0 + 180)
  timer.scheduleFunction(heartbeat, nil, t0 + 120)
  timer.scheduleFunction(topUp, nil, t0 + 200)
  ST.log(string.format("started: %d lanes, %d fishing regions, cap %d",
                       #(ST.cfg.lanes or {}), #(ST.cfg.fishing or {}),
                       ST.cfg.maxActive or 25))
end

start()
