/**
 * Airbase Reference Card — shared mission-wide kneeboard card.
 * Shows airbases with coordinates and coalition.
 */

import { forward as toMGRS } from 'mgrs';
import { cardRoot, headerStyle, titleStyle, subtitleStyle, sectionTitle, cell, th, notesBox, DIM, ACCENT, ROW_ALT, footerStyle } from './cardStyles';
import type { Airbase } from '../types/mission';

interface AirbaseRefCardProps {
  airbases: Airbase[];
  theater: string;
}

function fmtCoord(lat?: number, lon?: number): string {
  if (lat == null || lon == null) return '—';
  try { return toMGRS([lon, lat], 3); } catch { return '—'; }
}

function fmtLatLon(lat?: number, lon?: number): string {
  if (lat == null || lon == null) return '—';
  const ns = lat >= 0 ? 'N' : 'S';
  const ew = lon >= 0 ? 'E' : 'W';
  const la = Math.abs(lat);
  const lo = Math.abs(lon);
  return `${ns}${Math.floor(la)}°${((la % 1) * 60).toFixed(1)}' ${ew}${Math.floor(lo)}°${((lo % 1) * 60).toFixed(1)}'`;
}

export function AirbaseRefCard({ airbases, theater }: AirbaseRefCardProps) {
  // Sort by name
  const sorted = [...airbases].sort((a, b) => a.name.localeCompare(b.name));

  return (
    <div style={{ ...cardRoot, position: 'relative' }}>
      <div style={headerStyle}>
        <div style={titleStyle}>AIRBASE REFERENCE</div>
        <div style={subtitleStyle}>
          {theater} | {sorted.length} airfield{sorted.length !== 1 ? 's' : ''}
        </div>
      </div>

      <table style={{ width: '100%', borderCollapse: 'collapse', flexShrink: 0 }}>
        <thead>
          <tr>
            <th style={{ ...th, textAlign: 'left' }}>AIRFIELD</th>
            <th style={{ ...th, width: 130 }}>MGRS</th>
            <th style={{ ...th, width: 180 }}>LAT/LON</th>
            <th style={{ ...th, width: 60 }}>SIDE</th>
          </tr>
        </thead>
        <tbody>
          {sorted.map((ab, i) => (
            <tr key={ab.name + i} style={{ background: i % 2 === 0 ? 'transparent' : ROW_ALT }}>
              <td style={{ ...cell, fontWeight: 500 }}>{ab.name}</td>
              <td style={{ ...cell, textAlign: 'center', color: DIM }}>{fmtCoord(ab.lat, ab.lon)}</td>
              <td style={{ ...cell, textAlign: 'center', color: DIM }}>{fmtLatLon(ab.lat, ab.lon)}</td>
              <td style={{
                ...cell,
                textAlign: 'center',
                color: ab.coalition === 'blue' ? ACCENT : ab.coalition === 'red' ? '#d95050' : DIM,
              }}>
                {(ab.coalition || 'neutral').toUpperCase()}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      {sorted.length === 0 && (
        <div style={{ padding: '20px 16px', fontSize: 17, color: DIM, textAlign: 'center' }}>
          No airbase data available for this theater.
        </div>
      )}

      {/* Notes */}
      <div style={{ display: 'flex', flexDirection: 'column', flex: 1, minHeight: 0, marginTop: 8 }}>
        <div style={sectionTitle}>NOTES</div>
        <div style={notesBox} />
      </div>

      <div style={footerStyle}>Generated by DCS Mission Planner | VMFA-224(AW)</div>
    </div>
  );
}
