/**
 * Airbase Reference Card — shared mission-wide kneeboard card.
 * Shows airbases with comms, TACAN, ILS, and active runways.
 */

import { cardRoot, headerStyle, titleStyle, subtitleStyle, cell, th, DIM, ACCENT, ROW_ALT, footerStyle } from './cardStyles';
import type { Airbase } from '../types/mission';
import { getAirbaseComms } from '../data/airbaseComms';

interface AirbaseRefCardProps {
  airbases: Airbase[];
  theater: string;
}

function fmtFreq(f?: number): string {
  if (f == null) return '—';
  return f.toFixed(f % 1 === 0 ? 1 : 2);
}

export function AirbaseRefCard({ airbases, theater }: AirbaseRefCardProps) {
  const sorted = [...airbases].sort((a, b) => a.name.localeCompare(b.name));

  const rows = sorted.map((ab) => {
    const comms = getAirbaseComms(ab.name);
    return { ab, comms };
  });

  return (
    <div style={{ ...cardRoot, position: 'relative' }}>
      <div style={headerStyle}>
        <div style={titleStyle}>AIRBASE REFERENCE</div>
        <div style={subtitleStyle}>
          {theater} | {sorted.length} airfield{sorted.length !== 1 ? 's' : ''}
        </div>
      </div>

      <table style={{ width: '100%', borderCollapse: 'collapse' }}>
        <thead>
          <tr>
            <th style={{ ...th, textAlign: 'left' }}>AIRFIELD</th>
            <th style={{ ...th, width: 58 }}>TWR</th>
            <th style={{ ...th, width: 58 }}>ATIS</th>
            <th style={{ ...th, width: 48 }}>TACAN</th>
            <th style={{ ...th, width: 100 }}>ILS</th>
            <th style={{ ...th, width: 110 }}>RWY</th>
            <th style={{ ...th, width: 38 }}>ELEV</th>
          </tr>
        </thead>
        <tbody>
          {rows.map(({ ab, comms }, i) => (
            <tr key={ab.name + i} style={{ background: i % 2 === 0 ? 'transparent' : ROW_ALT }}>
              <td style={{
                ...cell,
                fontWeight: 500,
                fontSize: 8,
                padding: '2px 4px',
                color: ab.coalition === 'blue' ? ACCENT : ab.coalition === 'red' ? '#d95050' : undefined,
              }}>
                {ab.name}
              </td>
              <td style={{ ...cell, textAlign: 'center', fontSize: 8, padding: '2px 3px' }}>
                {fmtFreq(comms?.tower)}
              </td>
              <td style={{ ...cell, textAlign: 'center', fontSize: 8, padding: '2px 3px' }}>
                {fmtFreq(comms?.atis)}
              </td>
              <td style={{ ...cell, textAlign: 'center', fontSize: 8, padding: '2px 3px', color: comms?.tacan ? ACCENT : DIM }}>
                {comms?.tacan || '—'}
              </td>
              <td style={{ ...cell, textAlign: 'center', fontSize: 7, padding: '2px 3px', color: DIM }}>
                {comms?.ils || '—'}
              </td>
              <td style={{ ...cell, textAlign: 'center', fontSize: 7, padding: '2px 3px' }}>
                {comms?.runways || '—'}
              </td>
              <td style={{ ...cell, textAlign: 'center', fontSize: 7, padding: '2px 3px', color: DIM }}>
                {comms?.elevation != null ? `${comms.elevation}'` : '—'}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      {sorted.length === 0 && (
        <div style={{ padding: '20px 16px', fontSize: 12, color: DIM, textAlign: 'center' }}>
          No airbase data available for this theater.
        </div>
      )}

      <div style={{ padding: '4px 16px 20px' }}>
        <div style={{ fontSize: 9, color: DIM, marginBottom: 3 }}>
          Freqs in MHz AM | ELEV in ft MSL | Data: DCS defaults
        </div>
      </div>

      <div style={footerStyle}>Generated by DCS Mission Planner | VMFA-224(AW)</div>
    </div>
  );
}
