/**
 * Mission Notes Card — shared (mission-wide) kneeboard card.
 *
 * Free-text notes the planner types in the Kneeboard tab. Unlike the
 * other cards (which derive everything from mission data), this one is
 * pure planner input — special instructions, ROE reminders, code-words,
 * contingency plans, whatever the flight needs on a card in the cockpit.
 *
 * Layout (600x850 fixed):
 *  - Header: title (default "MISSION NOTES") + squadron/theater/date
 *  - Body: the notes text, rendered verbatim with line breaks preserved
 *    (white-space: pre-wrap). Long text wraps; overflow past the bottom
 *    is clipped by cardRoot's overflow:hidden. v1 is single-page — if a
 *    planner regularly overflows we can paginate like ThreatCard does.
 *
 * Empty-state: if the planner enabled the card but typed nothing, we
 * render a placeholder so the card isn't a blank page (mirrors GoalsCard
 * / DmpiCard behaviour).
 */

import {
  cardRoot, headerStyle, titleStyle, subtitleStyle,
  notesBox, footerStyle, DIM, MissionDateLine,
} from './cardStyles';
import type { MissionOverviewData } from '../types/mission';

interface NotesCardProps {
  /** The planner's free-text notes. Line breaks preserved. */
  text: string;
  /** Optional custom heading. Falls back to "MISSION NOTES". */
  title?: string;
  /** Squadron / SOP name shown in the header subtitle. */
  squadron?: string;
  overview?: MissionOverviewData;
}

export function NotesCard({ text, title, squadron, overview }: NotesCardProps) {
  const heading = (title || '').trim() || 'MISSION NOTES';
  const body = (text || '').trim();

  return (
    <div style={cardRoot}>
      <div style={headerStyle}>
        <div style={titleStyle}>{heading}</div>
        {squadron && <div style={subtitleStyle}>{squadron}</div>}
        {overview && (
          <MissionDateLine
            date={overview.date}
            startTime={overview.start_time}
            theater={overview.theater}
            showTheater
          />
        )}
      </div>

      {body ? (
        <div
          style={{
            ...notesBox,
            // Preserve the planner's own line breaks + wrap long lines.
            // Slightly larger than the default notesBox font so the
            // text reads at cockpit distance.
            whiteSpace: 'pre-wrap',
            wordBreak: 'break-word',
            fontSize: 19,
            lineHeight: 1.4,
            overflow: 'hidden',
          }}
        >
          {body}
        </div>
      ) : (
        <div
          style={{
            ...notesBox,
            color: DIM,
            fontStyle: 'italic',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            textAlign: 'center',
          }}
        >
          No notes entered. Type mission notes in the Kneeboard tab to
          fill this card.
        </div>
      )}

      <div style={footerStyle}>
        Notes | Generated by DCS:OPT
      </div>
    </div>
  );
}
