/**
 * Radio Ladder Card — the frequencies a flight dials, in the order it dials
 * them.
 *
 * This card used to print every group in the coalition, deduped by frequency
 * and bucketed into role tiers — 41 rows on a Kola package. That is a roster,
 * not a ladder, and it left the pilot to work out which of those 41 they
 * would ever key. A ladder walks the sortie instead: ground, tower, check-in,
 * tactical, AWACS, tanker, recovery, guard. See radioLadder.ts for how each
 * rung is derived.
 *
 * Rung order can be overridden by the planner (drag-to-reorder in the
 * Kneeboard tab); `order` carries that preference.
 */

import {
  cardRoot, headerStyle, titleStyle, subtitleStyle, sectionTitle, cell, th,
  notesBox, TEXT, DIM, ACCENT, ROW_ALT, footerStyle, MissionDateLine,
} from './cardStyles';
import type { Airbase, MissionGroup, MissionOverviewData, RadioPresetRadio } from '../types/mission';
import { buildRadioLadder, applyLadderOrder } from './radioLadder';
import { presetLabel } from './radioPresets';

interface RadioLadderCardProps {
  groups: MissionGroup[];
  coalition: string;
  overview?: MissionOverviewData;
  /** The flight this ladder is for. Without it the card can still list the
   *  package-wide rungs, but not home plate or the intra-flight net. */
  group?: MissionGroup;
  airbases?: Airbase[];
  sopComms?: { role: string; frequency: number }[];
  /** Jet's programmed presets, for the CHAN column. */
  presets?: RadioPresetRadio[];
  /** Planner's custom rung order (row ids). */
  order?: string[];
  /** Planner-typed notes rendered inside the NOTES box. (v0.9.70) */
  notes?: string;
}

function formatFreq(freq: number, mod: number): string {
  // A carrier carries no group frequency in the .miz — its rung earns its
  // place on the TACAN alone, so print a dash rather than "0.000 AM".
  if (!(freq > 0)) return '—';
  return `${freq.toFixed(3)} ${mod === 0 ? 'AM' : 'FM'}`;
}

export function RadioLadderCard({
  groups, coalition, overview, group, airbases = [], sopComms = [],
  presets, order, notes,
}: RadioLadderCardProps) {
  const rows = applyLadderOrder(
    buildRadioLadder({ group, allGroups: groups, coalition, airbases, sopComms }),
    order,
  );

  return (
    <div style={{ ...cardRoot, position: 'relative' }}>
      <div style={headerStyle}>
        <div style={titleStyle}>RADIO LADDER</div>
        <div style={subtitleStyle}>
          {group ? group.groupName : coalition.toUpperCase()} | {rows.length} rungs
        </div>
        {overview && <MissionDateLine date={overview.date} startTime={overview.start_time} theater={overview.theater} showTheater />}
      </div>

      <table style={{ width: '100%', borderCollapse: 'collapse', tableLayout: 'fixed' }}>
        <thead>
          <tr>
            <th style={{ ...th, width: 28 }}>#</th>
            <th style={{ ...th, width: 96, textAlign: 'left' }}>PHASE</th>
            <th style={{ ...th, textAlign: 'left' }}>AGENCY</th>
            <th style={{ ...th, width: 118 }}>FREQUENCY</th>
            <th style={{ ...th, width: 58 }}>CHAN</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((r, i) => {
            const chan = presetLabel(r.freqMhz, presets);
            return (
              <tr key={r.id} style={{ background: i % 2 === 0 ? 'transparent' : ROW_ALT }}>
                <td style={{ ...cell, textAlign: 'center', color: ACCENT, fontWeight: 600 }}>{i + 1}</td>
                <td style={{ ...cell, color: DIM, fontSize: 16 }}>{r.phase}</td>
                <td style={{ ...cell, fontWeight: 500, overflow: 'hidden',
                             textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                  {r.agency}
                  {r.note && <span style={{ color: DIM, marginLeft: 5 }}>{r.note}</span>}
                </td>
                <td style={{ ...cell, textAlign: 'center',
                             color: r.freqMhz > 0 ? ACCENT : DIM, fontWeight: 600 }}>
                  {formatFreq(r.freqMhz, r.modulation)}
                </td>
                {/* The channel the jet already has this on — see radioPresets.ts. */}
                <td style={{ ...cell, textAlign: 'center', color: chan ? TEXT : DIM }}>
                  {chan ? chan.replace(/[()]/g, '') : '—'}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>

      {rows.length === 0 && (
        <div style={{ padding: '20px 16px', fontSize: 17, color: DIM, textAlign: 'center' }}>
          No radio frequencies found.
        </div>
      )}

      <div style={sectionTitle}>NOTES</div>
      <div style={notesBox}>
        {notes && notes.trim() && (
          <div style={{
            fontSize: 17, color: TEXT,
            whiteSpace: 'pre-wrap', wordBreak: 'break-word', lineHeight: 1.35,
          }}>
            {notes.trim()}
          </div>
        )}
      </div>

      <div style={footerStyle}>Generated by DCS:OPT | VMFA-224(AW)</div>
    </div>
  );
}
