/**
 * Route Detail Card — per-flight kneeboard card.
 *
 * Renders the flight's route on a terrain-tile map (route line, DEP/ARR/
 * waypoint markers, leg distances) plus a clean waypoint table. No threat
 * info at all — the dedicated Threat Card owns the threat picture; this
 * card stays a pure route-planning aid. (v0.9.73)
 */

import { cardRoot, headerStyle, titleStyle, subtitleStyle, sectionTitle, cell, th, BORDER, BG, TEXT, DIM, ACCENT, ROW_ALT, footerStyle, notesBox, FONT, W as CARD_W, MissionDateLine } from './cardStyles';
import type { MissionGroup, ThreatRing, MissionOverviewData, Waypoint } from '../types/mission';
import { getAircraftType } from '../utils/groups';
import { metersToFeet } from '../utils/conversions';
import { TileMap, createProjection } from './TileMap';
import { formatCoord, type CoordFormat } from './coords';

interface RouteDetailCardProps {
  group: MissionGroup;
  threats: ThreatRing[];
  overview?: MissionOverviewData;
  /** Planner-typed notes rendered inside the NOTES box. (v0.9.70) */
  notes?: string;
  /** Coordinate display format from the Kneeboard tab. (v0.9.76) */
  coordFormat?: CoordFormat;
}

export function RouteDetailCard({ group, overview, notes, coordFormat = 'mgrs' }: RouteDetailCardProps) {
  const airframe = getAircraftType(group);
  const wps = group.waypoints;

  return (
    <div style={{ ...cardRoot, position: 'relative' }}>
      <div style={headerStyle}>
        <div style={titleStyle}>ROUTE DETAIL — {group.groupName.toUpperCase()}</div>
        <div style={subtitleStyle}>
          {airframe} | {wps.length} waypoints
        </div>
        {overview && <MissionDateLine date={overview.date} startTime={overview.start_time} theater={overview.theater} showTheater />}
      </div>

      {/* Visual route map — terrain tiles with the flight's route line,
          DEP/ARR/WP markers and leg-distance labels. No threats: the
          Threat Card owns the threat picture; this card is pure route.
          (v0.9.73) Only renders when the route has ≥2 plottable waypoints. */}
      <RouteMap group={group} />

      {/* Route waypoint table — pure route detail, no threat columns. */}
      <div style={sectionTitle}>ROUTE WAYPOINTS</div>
      <table style={{ width: '100%', borderCollapse: 'collapse' }}>
        <thead>
          <tr>
            <th style={{ ...th, width: 34 }}>WP</th>
            <th style={{ ...th, textAlign: 'left' }}>NAME</th>
            <th style={{ ...th, width: coordFormat === 'mgrs' ? 120 : 150 }}>{coordFormat === 'mgrs' ? 'MGRS' : 'LAT/LON'}</th>
            <th style={{ ...th, width: 70 }}>ALT</th>
            <th style={{ ...th, width: 50 }}>HDG</th>
            <th style={{ ...th, width: 60 }}>DIST</th>
          </tr>
        </thead>
        <tbody>
          {wps.map((wp, i) => (
            <tr key={wp.waypoint_number} style={{ background: i % 2 === 0 ? 'transparent' : ROW_ALT }}>
              <td style={{ ...cell, textAlign: 'center', color: ACCENT, fontWeight: 600 }}>{wp.waypoint_number}</td>
              <td style={{ ...cell }}>{(wp.waypoint_name || '').substring(0, 14)}</td>
              <td style={{ ...cell, textAlign: 'center', color: DIM, fontSize: coordFormat === 'mgrs' ? 19 : 15 }}>{formatCoord(wp.lat, wp.lon, coordFormat, 3)}</td>
              <td style={{ ...cell, textAlign: 'right' }}>
                {Math.round(metersToFeet(wp.altitude_m)).toLocaleString()}
              </td>
              <td style={{ ...cell, textAlign: 'center', color: DIM }}>
                {wp.leg_bearing_deg != null ? `${Math.round(wp.leg_bearing_deg).toString().padStart(3, '0')}` : '—'}
              </td>
              <td style={{ ...cell, textAlign: 'right' }}>
                {wp.leg_distance_nm ? wp.leg_distance_nm.toFixed(1) : '—'}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* Notes — only rendered when the planner typed one, so a blank
          ruled box doesn't take space under the map. (v0.9.71) */}
      {notes && notes.trim() && (
        <>
          <div style={{ ...sectionTitle, marginTop: 6 }}>NOTES</div>
          <div style={notesBox}>
            <div style={{
              fontSize: 17, color: TEXT,
              whiteSpace: 'pre-wrap', wordBreak: 'break-word', lineHeight: 1.35,
            }}>
              {notes.trim()}
            </div>
          </div>
        </>
      )}

      <div style={footerStyle}>Generated by DCS:OPT | VMFA-224(AW)</div>
    </div>
  );
}

/* ------------------------------------------------------------------ */
/* Route Map — tile-backed map with the flight's route + threat rings  */
/* ------------------------------------------------------------------ */

// cardRoot has 12px padding each side → usable width is W - 24.
// Taller map (v0.9.72) now that the threat tables are gone — the card
// is mostly map + the route waypoint table.
const ROUTE_MAP_W = CARD_W - 24;
const ROUTE_MAP_H = 360;
const NICE_SCALE_NM = [5, 10, 20, 25, 50, 100, 150, 200, 300];

function RouteMap({ group }: { group: MissionGroup }) {
  // Plottable waypoints — need at least two to draw a line.
  const pts = group.waypoints.filter(
    (w): w is Waypoint & { lat: number; lon: number } => w.lat != null && w.lon != null,
  );
  if (pts.length < 2) return null;

  // Bound to the route, zoomed in tight on the flight path. (v0.9.72)
  let minLat = Infinity, maxLat = -Infinity, minLon = Infinity, maxLon = -Infinity;
  const extend = (lat: number, lon: number) => {
    minLat = Math.min(minLat, lat); maxLat = Math.max(maxLat, lat);
    minLon = Math.min(minLon, lon); maxLon = Math.max(maxLon, lon);
  };
  for (const p of pts) extend(p.lat, p.lon);

  // Enforce a minimum span so a short hop doesn't zoom to street level,
  // then pad 15% for surrounding terrain context.
  const MIN_SPAN_DEG = 0.12; // ≈ 13 nm
  const midLat = (minLat + maxLat) / 2;
  const midLon = (minLon + maxLon) / 2;
  if (maxLat - minLat < MIN_SPAN_DEG) { minLat = midLat - MIN_SPAN_DEG / 2; maxLat = midLat + MIN_SPAN_DEG / 2; }
  if (maxLon - minLon < MIN_SPAN_DEG) { minLon = midLon - MIN_SPAN_DEG / 2; maxLon = midLon + MIN_SPAN_DEG / 2; }
  const padLat = (maxLat - minLat) * 0.15;
  const padLon = (maxLon - minLon) * 0.15;
  minLat -= padLat; maxLat += padLat; minLon -= padLon; maxLon += padLon;

  const proj = createProjection(minLat, maxLat, minLon, maxLon, ROUTE_MAP_W, ROUTE_MAP_H);
  const projected = pts.map((p) => {
    const [x, y] = proj.project(p.lat, p.lon);
    return { x, y, wp: p };
  });
  const polyline = projected.map((p) => `${p.x.toFixed(1)},${p.y.toFixed(1)}`).join(' ');

  // Scale bar — largest "nice" nm distance whose pixel length fits ~110px.
  const pxPerNm = proj.metersToPixels(1852);
  let scaleNm = NICE_SCALE_NM[0];
  for (const n of NICE_SCALE_NM) { if (n * pxPerNm <= 110) scaleNm = n; }
  const scalePx = Math.max(8, scaleNm * pxPerNm);
  const scaleX1 = ROUTE_MAP_W - 14 - scalePx;
  const scaleY = ROUTE_MAP_H - 14;

  return (
    <div style={{ padding: '0 0 6px' }}>
      <div style={{ border: `1px solid ${BORDER}`, borderRadius: 4, overflow: 'hidden' }}>
        <TileMap
          width={ROUTE_MAP_W}
          height={ROUTE_MAP_H}
          minLat={minLat}
          maxLat={maxLat}
          minLon={minLon}
          maxLon={maxLon}
        >
          <svg width={ROUTE_MAP_W} height={ROUTE_MAP_H} style={{ display: 'block' }}>
            {/* Route line */}
            <polyline points={polyline} fill="none"
              stroke="#4ad0e0" strokeWidth={2.5} strokeOpacity={0.95}
              strokeLinejoin="round" strokeLinecap="round" />

            {/* Leg distance labels at each leg midpoint */}
            {projected.slice(1).map((b, i) => {
              const a = projected[i];
              const mx = (a.x + b.x) / 2;
              const my = (a.y + b.y) / 2;
              const distNm = b.wp.leg_distance_nm;
              if (!distNm) return null;
              return (
                <text key={`leg-${i}`} x={mx} y={my - 3} textAnchor="middle"
                  fontSize={9} fontFamily={FONT} fontWeight={600}
                  fill="#cfeff5" stroke={BG} strokeWidth={2.5} paintOrder="stroke">
                  {distNm.toFixed(0)}nm
                </text>
              );
            })}

            {/* Waypoint markers — first green / last red / mid amber.
                Labels prefer the user's actual waypoint name; only fall
                back to DEP/ARR/WPn when the name is blank or matches the
                generic auto-generated default (e.g. "WP0", "Point 1").
                Earlier code unconditionally relabeled the last waypoint
                "ARR" — but it's often a TGT or a fence point, not an
                arrival. (v1.19.22 — Fett reported "Neon" overwritten as
                "ARR" on a DEVIL 1 PP2 strike kneeboard.) */}
            {projected.map((p, i) => {
              const isFirst = i === 0;
              const isLast = i === projected.length - 1;
              const color = isFirst ? '#3fb950' : isLast ? '#d95050' : '#ffb24a';
              const rawName = (p.wp.waypoint_name || '').trim();
              const isDefaultName = !rawName
                || /^WP\s*\d+$/i.test(rawName)
                || /^Point\s+\d+$/i.test(rawName)
                || /^Waypoint\s*\d*$/i.test(rawName);
              const fallback = isFirst ? 'DEP' : isLast ? 'ARR' : `WP${p.wp.waypoint_number}`;
              const label = (isDefaultName ? fallback : rawName).substring(0, 6);
              const big = isFirst || isLast;
              return (
                <g key={`wp-${i}`}>
                  <circle cx={p.x} cy={p.y} r={big ? 6 : 4}
                    fill={color} stroke={BG} strokeWidth={1.5} />
                  <text x={p.x} y={p.y - (big ? 10 : 8)} textAnchor="middle"
                    fontSize={big ? 10 : 9} fontFamily={FONT} fontWeight={700}
                    fill={color} stroke={BG} strokeWidth={2.5} paintOrder="stroke">
                    {label}
                  </text>
                </g>
              );
            })}

            {/* Scale bar (bottom-right) */}
            <g>
              <rect x={scaleX1 - 4} y={scaleY - 12} width={scalePx + 8} height={20}
                fill="rgba(26,26,26,0.6)" rx={2} />
              <line x1={scaleX1} y1={scaleY} x2={scaleX1 + scalePx} y2={scaleY}
                stroke="#fff" strokeWidth={2} />
              <line x1={scaleX1} y1={scaleY - 3} x2={scaleX1} y2={scaleY + 3} stroke="#fff" strokeWidth={2} />
              <line x1={scaleX1 + scalePx} y1={scaleY - 3} x2={scaleX1 + scalePx} y2={scaleY + 3} stroke="#fff" strokeWidth={2} />
              <text x={scaleX1 + scalePx / 2} y={scaleY - 4} textAnchor="middle"
                fontSize={9} fontFamily={FONT} fontWeight={600} fill="#fff">
                {scaleNm} nm
              </text>
            </g>
          </svg>
        </TileMap>
      </div>
    </div>
  );
}
