/**
 * Weapon-employment kneeboard card — one store per page (paginated like the
 * Threat card). Renders envelope/range, employment profile, switchology, and
 * common mistakes for the selected weapons. Reference only — a disclaimer
 * reminds aircrew to verify against current NATOPS / the live DCS module.
 */

import { cardRoot, headerStyle, titleStyle, subtitleStyle, sectionTitle, footerStyle, BORDER, TEXT, DIM, ACCENT, MissionDateLine } from './cardStyles';
import type { MissionOverviewData } from '../types/mission';
import { WEAPONS, type WeaponSpec, type WeaponCategory } from './weaponData';

const CAT_COLOR: Record<WeaponCategory, string> = {
  'A/A': '#4a9eff', 'A/G': '#e8833a', 'Anti-ship': '#3fb950', 'Bomb': '#d29922', 'Gun': '#f85149',
};

/** Resolve a selected set of weapon ids (in WEAPONS order) for pagination. */
export function selectedWeapons(ids: string[]): WeaponSpec[] {
  const set = new Set(ids);
  return WEAPONS.filter((w) => set.has(w.id));
}
export function weaponCardPageCount(ids: string[]): number {
  return selectedWeapons(ids).length;
}

interface WeaponCardProps {
  weaponIds: string[];
  page?: number;
  overview?: MissionOverviewData;
}

export function WeaponCard({ weaponIds, page = 0, overview }: WeaponCardProps) {
  const list = selectedWeapons(weaponIds);
  const w = list[page];
  const total = list.length;
  if (!w) {
    return (
      <div style={cardRoot}>
        <div style={headerStyle}><div style={titleStyle}>WEAPON CARD</div></div>
        <div style={{ padding: '20px 16px', fontSize: 17, color: DIM, textAlign: 'center' }}>
          No weapons selected.
        </div>
      </div>
    );
  }
  const color = CAT_COLOR[w.category] || ACCENT;

  return (
    <div style={cardRoot}>
      <div style={headerStyle}>
        <div style={titleStyle}>
          {w.name.toUpperCase()}
          {total > 1 ? <span style={{ fontSize: 15, color: DIM, marginLeft: 8 }}>({page + 1}/{total})</span> : null}
          <span style={{ fontSize: 14, color, marginLeft: 10, fontWeight: 700, border: `1px solid ${color}`, borderRadius: 3, padding: '1px 7px' }}>{w.category}</span>
        </div>
        <div style={subtitleStyle}>{w.guidance} · {w.range}</div>
        {overview && <MissionDateLine date={overview.date} startTime={overview.start_time} theater={overview.theater} showTheater />}
      </div>

      {/* Envelope */}
      <div style={sectionTitle}>ENVELOPE</div>
      <div style={{ padding: '6px 16px', fontSize: 17, color: TEXT, lineHeight: 1.4, borderBottom: `1px solid ${BORDER}` }}>{w.envelope}</div>

      <Section title="EMPLOYMENT PROFILE" items={w.profile} accent={color} ordered />
      <Section title="SWITCHOLOGY" items={w.switchology} accent={ACCENT} ordered />
      <Section title="COMMON MISTAKES" items={w.mistakes} accent="#f85149" />

      {/* Disclaimer */}
      <div style={{ margin: '10px 16px', padding: '8px 12px', background: 'rgba(255,165,0,0.07)', border: `1px solid rgba(255,165,0,0.3)`, borderRadius: 4, fontSize: 13, color: '#cccccc', fontStyle: 'italic' }}>
        Reference only — verify against current NATOPS / the live DCS module before employment.
      </div>

      <div style={footerStyle}>Generated by DCS:OPT | VMFA-224(AW)</div>
    </div>
  );
}

function Section({ title, items, accent, ordered }: { title: string; items: string[]; accent: string; ordered?: boolean }) {
  return (
    <>
      <div style={sectionTitle}>{title}</div>
      <ol style={{ margin: 0, padding: '6px 16px 6px 38px', listStyle: ordered ? 'decimal' : 'disc', flexShrink: 0 }}>
        {items.map((it, i) => (
          <li key={i} style={{ fontSize: 17, color: TEXT, lineHeight: 1.4, padding: '2px 0', marginLeft: ordered ? 0 : 0 }}>
            <span style={{ color: accent, marginRight: 0 }} />{it}
          </li>
        ))}
      </ol>
    </>
  );
}
