/**
 * F10 Radio Menu Builder — generates a trigger rule that registers
 * F10 radio menu entries pilots can pick in-game to activate /
 * deactivate / destroy groups.
 *
 * Pattern: one triggerStart rule with an `a_do_script` action that
 * carries an `missionCommands.addCommandForCoalition(...)` call per
 * menu entry. Adding the rule via this builder doesn't replace
 * existing triggers — it appends one new one. The user can edit it
 * later in the Editor mode like any other rule, or regenerate from
 * here and delete the old one.
 *
 * Why a script-based approach instead of native trigger
 * a_add_radio_item actions? Two reasons:
 *  1. We can express "click → activate group" inline without having
 *     to manage flag IDs, dictionary entries, and a paired
 *     watcher rule per menu item. One trigger, N menu entries.
 *  2. Easier to read in the source — the generated Lua is
 *     self-documenting and matches what a hand-rolled DCS scripter
 *     would write.
 */

import { useState } from 'react';
import { useMissionStore } from '../../../store/missionStore';
import { useTriggerStore } from '../../../store/triggerStore';
import type { TriggerRule } from '../../../types/mission';
import { TextInput } from '../../../components/TextInput';
import { Select } from '../../../components/Select';
import { Button } from '../../../components/Button';

/** Menu entry user-facing types. */
type MenuCoalition = 'blue' | 'red' | 'all';
type MenuAction = 'activate' | 'deactivate' | 'destroy';

const COALITION_LABEL: Record<MenuCoalition, string> = {
  blue: 'Blue',
  red:  'Red',
  all:  'All',
};

const ACTION_LABEL: Record<MenuAction, string> = {
  activate:   'Activate group',
  deactivate: 'Deactivate group (AI off)',
  destroy:    'Destroy group',
};

const COALITION_COLOR: Record<MenuCoalition, string> = {
  blue: '#4a8fd4',
  red:  '#d95050',
  all:  '#aaaaaa',
};

interface MenuEntry {
  id: string;
  coalition: MenuCoalition;
  label: string;
  action: MenuAction;
  groupName: string;
}

function makeId(): string {
  return `f10_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 5)}`;
}

/** Lua-escape a string so it can sit inside a "..." literal. */
function escapeLuaString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, ' ');
}

/** Generate the body of the a_do_script action. One block per
 *  menu entry, plus a header comment so the generated rule is
 *  inspectable in the Editor without confusion. */
function generateScript(entries: MenuEntry[]): string {
  if (entries.length === 0) return '';

  const lines: string[] = [
    '-- F10 Radio Menu (generated by mizmaker)',
    '-- Edit in the Triggers > F10 Menus tab and re-generate to update.',
    '',
  ];

  for (const e of entries) {
    const labelEsc = escapeLuaString(e.label);
    const groupEsc = escapeLuaString(e.groupName);
    // Per-entry block. `pcall` around the action so a missing group
    // (typo / late activation order) doesn't kill the whole menu.
    const actionLua = (() => {
      switch (e.action) {
        case 'activate':
          return 'local g = Group.getByName(name); if g then g:activate() end';
        case 'deactivate':
          return 'local g = Group.getByName(name); if g then trigger.action.setGroupAIOff(g) end';
        case 'destroy':
          return 'local g = Group.getByName(name); if g then g:destroy() end';
      }
    })();

    if (e.coalition === 'all') {
      lines.push(
        `-- ${labelEsc} (${e.action} → ${groupEsc})`,
        `do`,
        `    local name = "${groupEsc}"`,
        `    missionCommands.addCommand("${labelEsc}", nil, function()`,
        `        ${actionLua}`,
        `    end)`,
        `end`,
        '',
      );
    } else {
      const coalConst = e.coalition === 'blue' ? 'coalition.side.BLUE' : 'coalition.side.RED';
      lines.push(
        `-- ${labelEsc} (${e.action} → ${groupEsc})`,
        `do`,
        `    local name = "${groupEsc}"`,
        `    missionCommands.addCommandForCoalition(${coalConst}, "${labelEsc}", nil, function()`,
        `        ${actionLua}`,
        `    end)`,
        `end`,
        '',
      );
    }
  }

  return lines.join('\n');
}

/** Build a complete TriggerRule from the menu entries. The store
 *  picks the next free numeric ID; we just provide the shape.
 *
 *  IMPORTANT: action `type` is 'DO_SCRIPT' (the backend's
 *  ACTION_TYPE_TO_PREDICATE key, not the raw Lua predicate
 *  'a_do_script'); and the script body lives in `params.lua`
 *  (not `params.script`). The backend's `_render_inline_action`
 *  reads exactly those keys — wrong names land an empty
 *  `["text"] = ""` on save and the user gets a no-op trigger
 *  in DCS-ME. (v0.9.34 — fixed silent drop reported during
 *  testing of v0.9.33.)
 */
function buildRule(entries: MenuEntry[], nextId: number): TriggerRule {
  const lua = generateScript(entries);
  return {
    id: nextId,
    name: 'F10 Radio Menu',
    enabled: true,
    oneTime: true,
    eventType: 'onMissionStart',
    conditions: [],
    actions: [
      {
        type: 'DO_SCRIPT',
        params: { lua },
      },
    ],
  };
}

interface F10MenuBuilderProps {
  /** Closes the builder pane / switches back to overview after
   *  the rule is added so the user can see the new entry. */
  onAdded?: () => void;
}

export function F10MenuBuilder({ onAdded }: F10MenuBuilderProps) {
  const groups = useMissionStore((s) => s.groups);
  const rules = useTriggerStore((s) => s.rules);
  // We use the store's full action interface so the new rule shows
  // up everywhere a regular rule does (Overview list, Editor, save
  // path, etc.) — no special casing.
  const setRules = useTriggerStore.setState;

  const [entries, setEntries] = useState<MenuEntry[]>([]);
  // Form scratch state for the "add row" — kept separate from the
  // committed list so the user can edit fields before clicking +.
  const [draft, setDraft] = useState<Omit<MenuEntry, 'id'>>({
    coalition: 'blue',
    label: '',
    action: 'activate',
    groupName: '',
  });

  const groupNames = groups.map((g) => g.groupName).sort((a, b) => a.localeCompare(b));

  const addEntry = () => {
    if (!draft.label.trim() || !draft.groupName) return;
    setEntries((prev) => [...prev, { ...draft, id: makeId() }]);
    setDraft({ coalition: draft.coalition, label: '', action: draft.action, groupName: '' });
  };

  const removeEntry = (id: string) => {
    setEntries((prev) => prev.filter((e) => e.id !== id));
  };

  const handleGenerate = () => {
    if (entries.length === 0) return;
    const nextId = (rules.length === 0 ? 1 : Math.max(...rules.map((r) => r.id)) + 1);
    const newRule = buildRule(entries, nextId);
    // Append directly via setState — the trigger store's addRule
    // creates a blank rule, which isn't what we want. We're adding
    // a fully-built rule and need to mark dirty.
    setRules((s) => ({
      rules: [...s.rules, newRule],
      isDirty: true,
      selectedRuleId: newRule.id,
    }));
    setEntries([]);
    onAdded?.();
  };

  const previewScript = generateScript(entries);

  return (
    <div style={{ padding: 12, maxWidth: 1000 }}>
      <h3 style={{ margin: '0 0 6px', color: '#e0e0e0', fontSize: 16 }}>
        F10 Radio Menu Builder
      </h3>
      <p style={{ margin: '0 0 14px', color: '#aaaaaa', fontSize: 13, lineHeight: 1.5 }}>
        Stage menu entries here, then click <strong style={{ color: '#3fb950' }}>Generate Trigger</strong>
        {' '}to add a single mission-start trigger that registers all of them via{' '}
        <code style={{ color: '#cccccc' }}>missionCommands.addCommandForCoalition</code>.
        Each entry can activate, deactivate, or destroy a group — pilots pick from the F10
        radio menu in-game.
      </p>

      {/* Add-row form */}
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: '120px 1fr 200px 1fr 60px',
          gap: 8,
          alignItems: 'center',
          padding: '10px 12px',
          background: '#0a1218',
          border: '1px solid #1a2a3a',
          borderRadius: 6,
          marginBottom: 12,
        }}
      >
        <Select
          size="sm"
          value={draft.coalition}
          onChange={(e) => setDraft({ ...draft, coalition: e.target.value as MenuCoalition })}
          style={{ color: COALITION_COLOR[draft.coalition], fontWeight: 600 }}
        >
          {(Object.keys(COALITION_LABEL) as MenuCoalition[]).map((c) => (
            <option key={c} value={c}>{COALITION_LABEL[c]}</option>
          ))}
        </Select>
        <TextInput
          size="sm"
          value={draft.label}
          onChange={(e) => setDraft({ ...draft, label: e.target.value })}
          placeholder="Menu label (e.g. Activate SAM East)"
          onKeyDown={(e) => { if (e.key === 'Enter') addEntry(); }}
        />
        <Select
          size="sm"
          value={draft.action}
          onChange={(e) => setDraft({ ...draft, action: e.target.value as MenuAction })}
        >
          {(Object.keys(ACTION_LABEL) as MenuAction[]).map((a) => (
            <option key={a} value={a}>{ACTION_LABEL[a]}</option>
          ))}
        </Select>
        <Select
          size="sm"
          value={draft.groupName}
          onChange={(e) => setDraft({ ...draft, groupName: e.target.value })}
        >
          <option value="">— pick group —</option>
          {groupNames.map((n) => (
            <option key={n} value={n}>{n}</option>
          ))}
        </Select>
        <Button
          variant="success"
          size="sm"
          onClick={addEntry}
          disabled={!draft.label.trim() || !draft.groupName}
        >
          + Add
        </Button>
      </div>

      {/* Staged entries */}
      {entries.length === 0 ? (
        <div
          style={{
            padding: '24px 16px',
            textAlign: 'center',
            color: '#888',
            background: 'rgba(74, 143, 212, 0.04)',
            border: '1px dashed #3a3a3a',
            borderRadius: 6,
            fontSize: 13,
          }}
        >
          No menu entries staged yet. Use the form above to add one.
        </div>
      ) : (
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13, marginBottom: 12 }}>
          <thead>
            <tr style={{ borderBottom: '2px solid #3a3a3a' }}>
              <th style={th}>SIDE</th>
              <th style={th}>LABEL</th>
              <th style={th}>ACTION</th>
              <th style={th}>TARGET GROUP</th>
              <th style={{ ...th, width: 60 }}></th>
            </tr>
          </thead>
          <tbody>
            {entries.map((e) => (
              <tr key={e.id} style={{ borderBottom: '1px solid #262626' }}>
                <td style={{ ...td, color: COALITION_COLOR[e.coalition], fontWeight: 600 }}>
                  {COALITION_LABEL[e.coalition]}
                </td>
                <td style={{ ...td, color: '#e0e0e0' }}>{e.label}</td>
                <td style={{ ...td, color: '#cccccc' }}>{ACTION_LABEL[e.action]}</td>
                <td style={{ ...td, color: '#cccccc', fontFamily: "'B612 Mono', monospace" }}>
                  {e.groupName}
                </td>
                <td style={td}>
                  <Button
                    variant="danger"
                    size="sm"
                    onClick={() => removeEntry(e.id)}
                    title="Remove entry"
                    style={{ padding: '2px 8px', fontSize: 11 }}
                  >
                    ×
                  </Button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}

      {/* Generated script preview + Generate button */}
      {entries.length > 0 && (
        <>
          <div
            style={{
              fontSize: 11,
              color: '#888',
              textTransform: 'uppercase',
              letterSpacing: 1,
              fontWeight: 600,
              marginBottom: 6,
            }}
          >
            Generated Lua (preview)
          </div>
          <pre
            style={{
              margin: 0,
              padding: '10px 14px',
              background: '#0a0f14',
              border: '1px solid #1a2a3a',
              borderRadius: 6,
              fontSize: 11,
              fontFamily: "'B612 Mono', monospace",
              color: '#cccccc',
              maxHeight: 240,
              overflow: 'auto',
              whiteSpace: 'pre',
            }}
          >
            {previewScript}
          </pre>
          <div style={{ marginTop: 12, display: 'flex', gap: 8 }}>
            <Button variant="success" onClick={handleGenerate}>
              Generate Trigger ({entries.length} entr{entries.length === 1 ? 'y' : 'ies'})
            </Button>
            <span style={{ color: '#888', fontSize: 12, alignSelf: 'center' }}>
              → adds one mission-start rule to the trigger list. Don't forget to{' '}
              <strong style={{ color: '#cccccc' }}>Save Triggers</strong> after.
            </span>
          </div>
        </>
      )}
    </div>
  );
}

const th: React.CSSProperties = {
  textAlign: 'left',
  padding: '6px 8px',
  color: '#aaaaaa',
  fontSize: 11,
  fontWeight: 600,
  textTransform: 'uppercase',
  letterSpacing: 0.5,
};

const td: React.CSSProperties = {
  padding: '6px 8px',
  verticalAlign: 'middle',
};
